<?xml version="1.0"?>
<!DOCTYPE HPCToolkitExperiment [
<!-- ******************************************************************** -->
<!-- HPCToolkit Experiment DTD						  -->
<!-- Version 2.2							  -->
<!-- ******************************************************************** -->
<!ELEMENT HPCToolkitExperiment (Header, (SecCallPathProfile|SecFlatProfile)*)>
<!ATTLIST HPCToolkitExperiment
	  version CDATA #REQUIRED>

  <!-- ****************************************************************** -->

  <!-- Info/NV: flexible name-value pairs: (n)ame; (t)ype; (v)alue -->
  <!ELEMENT Info (NV*)>
  <!ATTLIST Info
	    n CDATA #IMPLIED>
  <!ELEMENT NV EMPTY>
  <!ATTLIST NV
	    n CDATA #REQUIRED
	    t CDATA #IMPLIED
	    v CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Header								  -->
  <!-- ****************************************************************** -->
  <!ELEMENT Header (Info*)>
  <!ATTLIST Header
	    n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section Header							  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecHeader (MetricTable?, MetricDBTable?, TraceDBTable?, LoadModuleTable?, FileTable?, ProcedureTable?, Info*)>

    <!-- MetricTable: -->
    <!ELEMENT MetricTable (Metric)*>

    <!-- Metric: (i)d; (n)ame -->
    <!--   o: metric sequence order (hpcrun metric order) -->
    <!--   md: metric description -->
    <!--   mp: metric parent ID   -->
    <!--   es: number of samples    (perf_events only) -->
    <!--   em: event multiplexed    (perf_events only) -->
    <!--   ep: average event period (perf_events only) -->
    <!--   (v)alue-type: transient type of values -->
    <!--   (t)ype: persistent type of metric      -->
    <!--   show: metric visibility type. Possible values: -->
    <!--        0: hidden -->
    <!--        1: shown  -->
    <!--        2: show inclusive metric only -->
    <!--        3: show exclusive metric only -->
    <!--        4: invisible, do not show at all -->
    <!--   show-percent: whether to show the percent (1) or not (0)  -->
    <!--   partner: the exclusive or inclusive partner ID of this metric -->
    <!--   fmt: format; show; -->
    <!ELEMENT Metric (MetricFormula*, Info?)>
    <!ATTLIST Metric
	      i            CDATA #REQUIRED
	      o	           CDATA #IMPLIED
	      n            CDATA #REQUIRED
	      md           CDATA #IMPLIED
	      mp           CDATA #IMPLIED
	      es           CDATA #IMPLIED
	      em           CDATA #IMPLIED
	      ep           CDATA #IMPLIED
	      v            (raw|final|derived-incr|derived) "raw"
	      t            (inclusive|exclusive|nil) "nil"
	      partner      CDATA #IMPLIED
	      fmt          CDATA #IMPLIED
	      show         (1|0|2|3|4) "1"
	      show-percent (1|0) "1">

    <!-- MetricFormula represents derived metrics: (t)ype; (frm): formula -->
    <!ELEMENT MetricFormula (Info?)>
    <!ATTLIST MetricFormula
	      t   (combine|finalize|view) "finalize"
	      i   CDATA #IMPLIED
	      frm CDATA #REQUIRED>

    <!-- Metric data, used in sections: (n)ame [from Metric]; (v)alue -->
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	      n CDATA #REQUIRED
	      v CDATA #REQUIRED>

    <!-- MetricDBTable: -->
    <!ELEMENT MetricDBTable (MetricDB)*>

    <!-- MetricDB: (i)d; (n)ame -->
    <!--   (t)ype: persistent type of metric -->
    <!--   db-glob:        file glob describing files in metric db -->
    <!--   db-id:          id within metric db -->
    <!--   db-num-metrics: number of metrics in db -->
    <!--   db-header-sz:   size (in bytes) of a db file header -->
    <!ELEMENT MetricDB EMPTY>
    <!ATTLIST MetricDB
	      i              CDATA #REQUIRED
	      n              CDATA #REQUIRED
	      t              (inclusive|exclusive|nil) "nil"
	      partner        CDATA #IMPLIED
	      db-glob        CDATA #IMPLIED
	      db-id          CDATA #IMPLIED
	      db-num-metrics CDATA #IMPLIED
	      db-header-sz   CDATA #IMPLIED>

    <!-- TraceDBTable: -->
    <!ELEMENT TraceDBTable (TraceDB)>

    <!-- TraceDB: (i)d -->
    <!--   u: unit time of the trace (ms, ns, ..) -->
    <!--   db-min-time: min beginning time stamp (global) -->
    <!--   db-max-time: max ending time stamp (global) -->
    <!ELEMENT TraceDB EMPTY>
    <!ATTLIST TraceDB
	      i            CDATA #REQUIRED
	      u            CDATA #IMPLIED
	      db-glob      CDATA #IMPLIED
	      db-min-time  CDATA #IMPLIED
	      db-max-time  CDATA #IMPLIED
	      db-header-sz CDATA #IMPLIED>

    <!-- LoadModuleTable assigns a short name to a load module -->
    <!ELEMENT LoadModuleTable (LoadModule)*>

    <!ELEMENT LoadModule (Info?)>
    <!ATTLIST LoadModule
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- FileTable assigns a short name to a file -->
    <!ELEMENT FileTable (File)*>

    <!ELEMENT File (Info?)>
    <!ATTLIST File
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- ProcedureTable assigns a short name to a procedure -->
    <!ELEMENT ProcedureTable (Procedure)*>

    <!-- Dictionary for procedure: (i)d, (n)ame, (f)eature and (v)alue of the address -->
    <!-- Possible value of f: -->
    <!-- 0: normal procedure -->
    <!-- 1: place holder, do not add anything -->
    <!-- 2: root-type, has to be shown in a separate view -->
    <!-- 3: invisible in hpcviewer, but visible in hpctraceviewer  -->
    <!ELEMENT Procedure (Info?)>
    <!ATTLIST Procedure
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED
	      f CDATA #IMPLIED
	      v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Call path profile					  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecCallPathProfile (SecHeader, SecCallPathProfileData)>
  <!ATTLIST SecCallPathProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecCallPathProfileData (PF|M)*>
      <!-- Procedure frame -->
      <!--   (i)d: unique identifier for cross referencing -->
      <!--   (s)tatic scope id -->
      <!--   (n)ame: a string or an id in ProcedureTable -->
      <!--   (lm) load module: a string or an id in LoadModuleTable -->
      <!--   (f)ile name: a string or an id in LoadModuleTable -->
      <!--   (l)ine range: "beg-end" (inclusive range) -->
      <!--   (a)lien: whether frame is alien to enclosing P -->
      <!--   (str)uct: hpcstruct node id -->
      <!--   (v)ma-range-set: "{[beg-end), [beg-end)...}" -->
      <!ELEMENT PF (PF|Pr|L|C|S|M)*>
      <!ATTLIST PF
		i  CDATA #IMPLIED
		s  CDATA #IMPLIED
		n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Procedure (static): GOAL: replace with 'P' -->
      <!ELEMENT Pr (Pr|L|C|S|M)*>
      <!ATTLIST Pr
                i  CDATA #IMPLIED
		s  CDATA #IMPLIED
                n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
                l  CDATA #IMPLIED
		a  (1|0) "0"
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Callsite (a special StatementRange) -->
      <!ELEMENT C (PF|M)*>
      <!ATTLIST C
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Flat profile						  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecFlatProfile (SecHeader, SecFlatProfileData)>
  <!ATTLIST SecFlatProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecFlatProfileData (LM|M)*>
      <!-- Load module: (i)d; (n)ame; (v)ma-range-set -->
      <!ELEMENT LM (F|P|M)*>
      <!ATTLIST LM
                i CDATA #IMPLIED
                n CDATA #REQUIRED
		v CDATA #IMPLIED>
      <!-- File -->
      <!ELEMENT F (P|L|S|M)*>
      <!ATTLIST F
                i CDATA #IMPLIED
                n CDATA #REQUIRED>
      <!-- Procedure (Note 1) -->
      <!ELEMENT P (P|A|L|S|C|M)*>
      <!ATTLIST P
                i CDATA #IMPLIED
                n CDATA #REQUIRED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Alien (Note 1) -->
      <!ELEMENT A (A|L|S|C|M)*>
      <!ATTLIST A
                i CDATA #IMPLIED
                f CDATA #IMPLIED
                n CDATA #IMPLIED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Loop (Note 1,2) -->
      <!ELEMENT L (A|Pr|L|S|C|M)*>
      <!ATTLIST L
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
	        f CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Statement (Note 2) -->
      <!--   (it): trace record identifier -->
      <!ELEMENT S (S|M)*>
      <!ATTLIST S
		i  CDATA #IMPLIED
		it CDATA #IMPLIED
		s  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Note 1: Contained Cs may not contain PFs -->
      <!-- Note 2: The 's' attribute is not used for flat profiles -->
]>
<HPCToolkitExperiment version="2.2">
<Header n="miniapp">
  <Info/>
</Header>
<SecCallPathProfile i="0" n="miniapp">
<SecHeader>
  <MetricTable>
    <Metric i="24" n="CPUTIME (sec):Sum (I)" o="0" v="derived-incr" md="CPUTIME (sec)" em="0" es="0" ep="0" t="inclusive" partner="25" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($24, $24)"/>
      <MetricFormula t="finalize" frm="$24"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="25" n="CPUTIME (sec):Sum (E)" o="-1" v="derived-incr" md="CPUTIME (sec)" em="0" es="0" ep="0" t="exclusive" partner="24" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($25, $25)"/>
      <MetricFormula t="finalize" frm="$25"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
  </MetricTable>
  <MetricDBTable>
  </MetricDBTable>
  <TraceDBTable>
    <TraceDB i="0" u="1000000000" db-glob="*.hpctrace" db-min-time="1596577315785418000" db-max-time="1596577316554350000" db-header-sz="32"/>
  </TraceDBTable>
  <LoadModuleTable>
    <LoadModule i="2" n="/home/u10/ianbertolacci/testcode/HPCToolkit-Testing-Miniapp/mpi_omp/miniapp"/>
    <LoadModule i="649" n="&lt;unknown load module&gt;"/>
    <LoadModule i="653" n="/opt/ohpc/pub/apps/hpctoolkit/2020.06/linux-centos7-zen/gcc-8.3.0/hpctoolkit-2020.06.12-eihbyb4brvhwsp2znuoxozo7uwus7y4n/lib/hpctoolkit/libhpcrun.so.0.0.0"/>
    <LoadModule i="657" n="/opt/ohpc/pub/apps/hpctoolkit/2020.06/linux-centos7-zen/gcc-8.3.0/hpctoolkit-2020.06.12-eihbyb4brvhwsp2znuoxozo7uwus7y4n/lib/hpctoolkit/ext-libs/libmonitor.so.0.0.0"/>
    <LoadModule i="669" n="/usr/lib64/libm-2.17.so"/>
    <LoadModule i="673" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/libmpi.so.40.10.4"/>
    <LoadModule i="693" n="/opt/ohpc/pub/compiler/gcc/8.3.0/lib64/libgomp.so.1.0.0"/>
    <LoadModule i="716" n="/usr/lib64/libpthread-2.17.so"/>
    <LoadModule i="731" n="/usr/lib64/libc-2.17.so"/>
    <LoadModule i="756" n="/usr/lib64/ld-2.17.so"/>
    <LoadModule i="766" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/libopen-rte.so.40.10.4"/>
    <LoadModule i="776" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/libopen-pal.so.40.10.4"/>
    <LoadModule i="809" n="/usr/lib64/libhwloc.so.5.7.5"/>
    <LoadModule i="815" n="/usr/lib64/libevent-2.0.so.5.1.9"/>
    <LoadModule i="823" n="/usr/lib64/libltdl.so.7.3.0"/>
    <LoadModule i="827" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_ess_pmi.so"/>
    <LoadModule i="833" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_pmix_ext2x.so"/>
    <LoadModule i="839" n="/opt/ohpc/admin/pmix/lib/libpmix.so.2.1.22"/>
    <LoadModule i="866" n="/usr/lib64/libibverbs.so.1.5.22.4"/>
    <LoadModule i="876" n="/usr/lib64/libbnxt_re-rdmav22.so"/>
    <LoadModule i="880" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_rcache_grdma.so"/>
    <LoadModule i="884" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_btl_vader.so"/>
    <LoadModule i="888" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_btl_openib.so"/>
    <LoadModule i="901" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_pml_ob1.so"/>
  </LoadModuleTable>
  <FileTable>
    <File i="3" n="./src/home/u10/ianbertolacci/testcode/HPCToolkit-Testing-Miniapp/mpi_omp/miniapp.c"/>
    <File i="650" n="&lt;unknown file&gt;"/>
    <File i="654" n="&lt;unknown file&gt; [libhpcrun.so.0.0.0]"/>
    <File i="658" n="&lt;unknown file&gt; [libmonitor.so.0.0.0]"/>
    <File i="670" n="e_log10.c"/>
    <File i="674" n="&lt;unknown file&gt; [libmpi.so.40.10.4]"/>
    <File i="694" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/parallel.c"/>
    <File i="698" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/team.c"/>
    <File i="701" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/alloc.c"/>
    <File i="706" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/linux/bar.c"/>
    <File i="709" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/linux/x86/futex.h"/>
    <File i="713" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/task.c"/>
    <File i="717" n="&lt;unknown file&gt; [libpthread-2.17.so]"/>
    <File i="720" n="old_pthread_cond_wait.c"/>
    <File i="732" n="&lt;unknown file&gt; [libc-2.17.so]"/>
    <File i="735" n="getsubopt.c"/>
    <File i="757" n="dl-profile.c"/>
    <File i="767" n="&lt;unknown file&gt; [libopen-rte.so.40.10.4]"/>
    <File i="777" n="&lt;unknown file&gt; [libopen-pal.so.40.10.4]"/>
    <File i="792" n="alfg.c"/>
    <File i="810" n="&lt;unknown file&gt; [libhwloc.so.5.7.5]"/>
    <File i="816" n="&lt;unknown file&gt; [libevent-2.0.so.5.1.9]"/>
    <File i="824" n="&lt;unknown file&gt; [libltdl.so.7.3.0]"/>
    <File i="828" n="crtstuff.c"/>
    <File i="834" n="&lt;unknown file&gt; [mca_pmix_ext2x.so]"/>
    <File i="840" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/client/pmix_client.c"/>
    <File i="858" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/threads/mutex_unix.h"/>
    <File i="846" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/runtime/pmix_progress_threads.c"/>
    <File i="855" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/runtime/pmix_finalize.c"/>
    <File i="867" n="&lt;unknown file&gt; [libibverbs.so.1.5.22.4]"/>
    <File i="877" n="&lt;unknown file&gt; [libbnxt_re-rdmav22.so]"/>
    <File i="881" n="crtstuff.c"/>
    <File i="885" n="btl_vader_module.c"/>
    <File i="889" n="crtstuff.c"/>
    <File i="896" n="&lt;unknown file&gt; [mca_btl_openib.so]"/>
    <File i="902" n="&lt;unknown file&gt; [mca_pml_ob1.so]"/>
    <File i="915" n="pml_ob1_iprobe.c"/>
  </FileTable>
  <ProcedureTable>
    <Procedure i="358" n="allocate_distributed_array" v="0x4026a0"/>
    <Procedure i="440" n="init_distributed_array" v="0x4029d0"/>
    <Procedure i="53" n="init_distributed_array._omp_fn.2" v="0x4015b0"/>
    <Procedure i="64" n="in_place_stencilize_local_array._omp_fn.3" v="0x401770"/>
    <Procedure i="459" n="in_place_stencilize_distributed_array" v="0x402ac0"/>
    <Procedure i="509" n="" v="0"/>
    <Procedure i="510" n="in_place_stencilize_local_array" v="0"/>
    <Procedure i="71" n="sum_local_array._omp_fn.4" v="0x4018f0"/>
    <Procedure i="527" n="sum_distributed_array" v="0x402ed0"/>
    <Procedure i="548" n="sum_local_array" v="0"/>
    <Procedure i="4" n="main" v="0x401200"/>
    <Procedure i="37" n="program_finalize" v="0"/>
    <Procedure i="651" n="&lt;partial call paths&gt;" f="1" v="0"/>
    <Procedure i="655" n="&lt;no activity&gt;" f="3" v="0"/>
    <Procedure i="659" n="&lt;program root&gt;" f="4" v="0"/>
    <Procedure i="665" n="MPI_Finalize" v="0"/>
    <Procedure i="667" n="&lt;thread root&gt;" f="4" v="0"/>
    <Procedure i="671" n="__sin_avx" v="0"/>
    <Procedure i="679" n="MPI_Irecv" v="0"/>
    <Procedure i="681" n="PMPI_Wait" v="0"/>
    <Procedure i="683" n="ompi_request_default_wait" v="0"/>
    <Procedure i="685" n="PMPI_Gather" v="0"/>
    <Procedure i="687" n="ompi_coll_base_gather_intra_basic_linear" v="0"/>
    <Procedure i="689" n="ompi_mpi_finalize" v="0"/>
    <Procedure i="691" n="ompi_proc_finalize" v="0"/>
    <Procedure i="695" n="GOMP_parallel" v="0"/>
    <Procedure i="699" n="gomp_new_team" v="0"/>
    <Procedure i="711" n="gomp_team_start" v="0"/>
    <Procedure i="704" n="gomp_team_end" v="0"/>
    <Procedure i="702" n="gomp_malloc" v="0"/>
    <Procedure i="707" n="gomp_team_barrier_wait_end" v="0"/>
    <Procedure i="709" n="&lt;inline&gt;" v="0"/>
    <Procedure i="714" n="gomp_init_task" v="0"/>
    <Procedure i="718" n="__pthread_mutex_unlock" v="0"/>
    <Procedure i="725" n="pthread_mutex_lock" v="0"/>
    <Procedure i="721" n="_L_unlock_738" v="0"/>
    <Procedure i="723" n="__lll_unlock_wake" v="0"/>
    <Procedure i="727" n="_L_lock_941" v="0"/>
    <Procedure i="729" n="__lll_lock_wait" v="0"/>
    <Procedure i="733" n="ioctl" v="0"/>
    <Procedure i="752" n="__xstat" v="0"/>
    <Procedure i="754" n="epoll_wait" v="0"/>
    <Procedure i="736" n="__malloc" v="0"/>
    <Procedure i="738" n="_int_malloc" v="0"/>
    <Procedure i="740" n="sysmalloc" v="0"/>
    <Procedure i="742" n="_int_free" v="0"/>
    <Procedure i="744" n="__GI___libc_free" v="0"/>
    <Procedure i="746" n="__GI_sched_yield" v="0"/>
    <Procedure i="748" n="__GI___munmap" v="0"/>
    <Procedure i="750" n="malloc_consolidate" v="0"/>
    <Procedure i="758" n="_dl_runtime_resolve_xsavec" v="0"/>
    <Procedure i="760" n="_dl_fixup" v="0"/>
    <Procedure i="762" n="_dl_lookup_symbol_x" v="0"/>
    <Procedure i="764" n="do_lookup_x" v="0"/>
    <Procedure i="770" n="orte_finalize" v="0"/>
    <Procedure i="772" n="orte_ess_base_app_finalize" v="0"/>
    <Procedure i="774" n="orte_session_dir_finalize" v="0"/>
    <Procedure i="782" n="opal_progress" v="0"/>
    <Procedure i="784" n="opal_convertor_prepare_for_recv" v="0"/>
    <Procedure i="786" n="mca_base_framework_close" v="0"/>
    <Procedure i="788" n="mca_base_components_close" v="0"/>
    <Procedure i="790" n="mca_base_component_close" v="0"/>
    <Procedure i="801" n="opal_os_dirpath_destroy" v="0"/>
    <Procedure i="803" n="opal_finalize" v="0"/>
    <Procedure i="793" n="mca_btl_base_close" v="0"/>
    <Procedure i="795" n="opal_free_list_destruct" v="0"/>
    <Procedure i="797" n="opal_free_list_allocation_release" v="0"/>
    <Procedure i="799" n="mca_rcache_base_close" v="0"/>
    <Procedure i="805" n="group_find" v="0"/>
    <Procedure i="807" n="opal_hwloc_base_close" v="0"/>
    <Procedure i="811" n="hwloc_topology_destroy" v="0"/>
    <Procedure i="813" n="hwloc_topology_set_distance_matrix" v="0"/>
    <Procedure i="817" n="event_base_loopbreak" v="0"/>
    <Procedure i="819" n="event_base_loop" v="0"/>
    <Procedure i="821" n="_event_strlcpy" v="0"/>
    <Procedure i="825" n="lt_dlexit" v="0"/>
    <Procedure i="831" n="rte_finalize" v="0"/>
    <Procedure i="837" n="ext2x_client_finalize" v="0"/>
    <Procedure i="853" n="PMIx_Finalize" v="0"/>
    <Procedure i="858" n="&lt;inline&gt;" v="0"/>
    <Procedure i="864" n="progress_engine" v="0"/>
    <Procedure i="861" n="pmix_progress_thread_pause" v="0"/>
    <Procedure i="862" n="&lt;inline&gt;" v="0"/>
    <Procedure i="856" n="pmix_rte_finalize" v="0"/>
    <Procedure i="868" n="ibv_dereg_mr" v="0"/>
    <Procedure i="870" n="ibv_cmd_dereg_mr" v="0"/>
    <Procedure i="872" n="ibv_cmd_reg_dm_mr" v="0"/>
    <Procedure i="874" n="execute_ioctl" v="0"/>
    <Procedure i="878" n="&lt;unknown procedure&gt; 0x287c [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="882" n="mca_rcache_grdma_deregister" v="0"/>
    <Procedure i="886" n="mca_btl_vader_component_progress" v="0"/>
    <Procedure i="890" n="openib_dereg_mr" v="0"/>
    <Procedure i="892" n="btl_openib_component_progress" v="0"/>
    <Procedure i="894" n="poll_device" v="0"/>
    <Procedure i="899" n="device_destruct" v="0"/>
    <Procedure i="897" n="mca_btl_openib_finalize" v="0"/>
    <Procedure i="903" n="mca_pml_ob1_irecv" v="0"/>
    <Procedure i="905" n="mca_pml_ob1_recv_req_start" v="0"/>
    <Procedure i="907" n="mca_pml_ob1_recv_request_progress_match" v="0"/>
    <Procedure i="909" n="mca_pml_ob1_recv_frag_callback_match" v="0"/>
    <Procedure i="911" n="mca_pml_ob1_recv" v="0"/>
    <Procedure i="913" n="mca_pml_ob1_send" v="0"/>
    <Procedure i="916" n="mca_pml_ob1_send_inline.constprop.6" v="0"/>
    <Procedure i="918" n="mca_pml_ob1_component_close" v="0"/>
  </ProcedureTable>
  <Info/>
</SecHeader>
<SecCallPathProfileData>
<M n="24" v="2.56236"/>
<PF i="2" s="651" l="0" lm="649" f="650" n="651">
<M n="24" v="0.01475"/>
<C i="3" s="652" l="0" v="0x1">
<M n="24" v="0.01475"/>
<PF i="4" s="882" l="0" lm="880" f="881" n="882">
<M n="24" v="0.01475"/>
<C i="5" s="883" l="0" v="0x22e9">
<M n="24" v="0.01475"/>
<PF i="6" s="890" l="0" lm="888" f="889" n="890">
<M n="24" v="0.01475"/>
<C i="7" s="891" l="0" v="0xd6ad">
<M n="24" v="0.01475"/>
<PF i="8" s="868" l="0" lm="866" f="867" n="868">
<M n="24" v="0.01475"/>
<C i="9" s="869" l="0" v="0x127b3">
<M n="24" v="0.01475"/>
<PF i="10" s="878" l="0" lm="876" f="877" n="878">
<M n="24" v="0.01475"/>
<C i="11" s="879" l="0" v="0x287d">
<M n="24" v="0.01475"/>
<PF i="12" s="870" l="0" lm="866" f="867" n="870">
<M n="24" v="0.01475"/>
<C i="13" s="871" l="0" v="0xbed0">
<M n="24" v="0.01475"/>
<PF i="14" s="872" l="0" lm="866" f="867" n="872">
<M n="24" v="0.01475"/>
<C i="15" s="873" l="0" v="0xb082">
<M n="24" v="0.01475"/>
<PF i="16" s="872" l="0" lm="866" f="867" n="872">
<M n="24" v="0.01475"/>
<C i="17" s="873" l="0" v="0xac1f">
<M n="24" v="0.01475"/>
<PF i="18" s="874" l="0" lm="866" f="867" n="874">
<M n="24" v="0.01475"/>
<C i="19" s="875" l="0" v="0xba7f">
<M n="24" v="0.01475"/>
<PF i="20" s="733" l="0" lm="731" f="732" n="733">
<M n="24" v="0.01475"/><M n="25" v="0.01475"/>
<S i="21" s="734" l="0" it="181">
<M n="24" v="0.01475"/><M n="25" v="0.01475"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
<PF i="22" s="655" l="0" lm="653" f="654" n="655">
<S i="23" s="656" l="0" it="165"/>
</PF>
<PF i="24" s="659" l="0" lm="657" f="658" n="659">
<M n="24" v="1.45057"/>
<C i="25" s="660" l="0" v="0xd76a">
<M n="24" v="1.45057"/>
<PF i="26" s="4" l="858" lm="2" f="3" n="4">
<M n="24" v="1.45057"/>
<C i="27" s="21" l="868" v="0x401249">
<M n="24" v="4.6e-05"/>
<PF i="28" s="358" l="525" lm="2" f="3" n="358">
<M n="24" v="4.6e-05"/>
<C i="29" s="393" l="602" v="0x402711">
<M n="24" v="4.6e-05"/>
<PF i="30" s="736" l="0" lm="731" f="735" n="736">
<M n="24" v="4.6e-05"/>
<C i="31" s="737" l="0" v="0x856fc">
<M n="24" v="4.6e-05"/>
<PF i="32" s="738" l="0" lm="731" f="735" n="738">
<M n="24" v="4.6e-05"/>
<C i="33" s="739" l="0" v="0x828ca">
<M n="24" v="4.6e-05"/>
<PF i="34" s="740" l="0" lm="731" f="735" n="740">
<M n="24" v="4.6e-05"/><M n="25" v="4.6e-05"/>
<S i="35" s="741" l="0" it="77">
<M n="24" v="4.6e-05"/><M n="25" v="4.6e-05"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<C i="36" s="23" l="876" v="0x401260">
<M n="24" v="0.000201"/>
<PF i="37" s="440" l="640" lm="2" f="3" n="440">
<M n="24" v="0.000201"/>
<C i="38" s="445" l="643" v="0x4029f0">
<M n="24" v="0.000201"/>
<PF i="39" s="695" l="165" lm="693" f="694" n="695">
<M n="24" v="0.000201"/>
<C i="40" s="696" l="168" v="0xd93f">
<M n="24" v="0.000201"/>
<PF i="41" s="53" l="643" lm="2" f="3" n="53">
<M n="24" v="0.000201"/>
<L i="42" s="61" l="644" f="3" v="0x40174d">
<M n="24" v="0.000201"/>
<C i="43" s="63" l="644" v="0x401739">
<M n="24" v="0.000201"/>
<PF i="44" s="671" l="0" lm="669" f="670" n="671">
<M n="24" v="0.000201"/><M n="25" v="0.000201"/>
<S i="45" s="672" l="0" it="239">
<M n="24" v="0.000201"/><M n="25" v="0.000201"/>
</S>
</PF>
</C>
</L>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<L i="46" s="26" l="879" f="3" v="0x401280">
<M n="24" v="1.35299"/>
<C i="47" s="33" l="881" v="0x40128a">
<M n="24" v="1.03014"/>
<PF i="48" s="459" l="695" lm="2" f="3" n="459">
<M n="24" v="1.03014"/>
<C i="49" s="499" l="728" v="0x402de8">
<M n="24" v="0.002471"/>
<PF i="50" s="679" l="0" lm="673" f="674" n="679">
<M n="24" v="0.002471"/>
<C i="51" s="680" l="0" v="0x7a8e5">
<M n="24" v="0.002471"/>
<PF i="52" s="903" l="0" lm="901" f="902" n="903">
<M n="24" v="0.002471"/>
<C i="53" s="904" l="0" v="0x8d67">
<M n="24" v="0.002471"/>
<PF i="54" s="758" l="0" lm="756" f="757" n="758">
<M n="24" v="0.000474"/>
<C i="55" s="759" l="0" v="0x16a9a">
<M n="24" v="0.000474"/>
<PF i="56" s="760" l="0" lm="756" f="757" n="760">
<M n="24" v="0.000474"/>
<C i="57" s="761" l="0" v="0xedde">
<M n="24" v="0.000474"/>
<PF i="58" s="762" l="0" lm="756" f="757" n="762">
<M n="24" v="0.000474"/>
<C i="59" s="763" l="0" v="0xa08f">
<M n="24" v="0.000474"/>
<PF i="60" s="764" l="0" lm="756" f="757" n="764">
<M n="24" v="0.000474"/><M n="25" v="0.000474"/>
<S i="61" s="765" l="0" it="83">
<M n="24" v="0.000474"/><M n="25" v="0.000474"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
<PF i="62" s="905" l="0" lm="901" f="902" n="905">
<M n="24" v="0.001997"/>
<C i="63" s="906" l="0" v="0x19597">
<M n="24" v="0.001997"/>
<PF i="64" s="784" l="0" lm="776" f="777" n="784">
<M n="24" v="0.001997"/><M n="25" v="0.001997"/>
<S i="65" s="785" l="0" it="249">
<M n="24" v="0.001997"/><M n="25" v="0.001997"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<C i="66" s="503" l="746" v="0x402ba9">
<M n="24" v="0.000995"/>
<PF i="67" s="679" l="0" lm="673" f="674" n="679">
<M n="24" v="0.000995"/>
<C i="68" s="680" l="0" v="0x7a8e5">
<M n="24" v="0.000995"/>
<PF i="69" s="903" l="0" lm="901" f="902" n="903">
<M n="24" v="0.000995"/>
<C i="70" s="904" l="0" v="0x8d67">
<M n="24" v="0.000995"/>
<PF i="71" s="905" l="0" lm="901" f="902" n="905">
<M n="24" v="0.000995"/>
<C i="72" s="906" l="0" v="0x197fa">
<M n="24" v="0.000995"/>
<PF i="73" s="907" l="0" lm="901" f="902" n="907">
<M n="24" v="0.000995"/><M n="25" v="0.000995"/>
<S i="74" s="908" l="0" it="251">
<M n="24" v="0.000995"/><M n="25" v="0.000995"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<C i="75" s="504" l="767" v="0x402c4a">
<M n="24" v="0.057853"/>
<PF i="76" s="681" l="0" lm="673" f="674" n="681">
<M n="24" v="0.057853"/>
<C i="77" s="682" l="0" v="0x8dca2">
<M n="24" v="0.057853"/>
<PF i="78" s="683" l="0" lm="673" f="674" n="683">
<M n="24" v="0.057853"/><M n="25" v="0.003991"/>
<C i="79" s="684" l="0" v="0x4a715">
<M n="24" v="0.053862"/>
<PF i="80" s="746" l="0" lm="731" f="735" n="746">
<M n="24" v="0.027009"/><M n="25" v="0.027009"/>
<S i="81" s="747" l="0" it="99">
<M n="24" v="0.027009"/><M n="25" v="0.027009"/>
</S>
</PF>
<PF i="82" s="782" l="0" lm="776" f="777" n="782">
<M n="24" v="0.026853"/>
<C i="83" s="783" l="0" v="0x2856c">
<M n="24" v="0.024858"/>
<PF i="84" s="886" l="0" lm="884" f="885" n="886">
<M n="24" v="0.024858"/><M n="25" v="0.018953"/>
<C i="85" s="887" l="0" v="0x42df">
<M n="24" v="0.000915"/>
<PF i="86" s="758" l="0" lm="756" f="757" n="758">
<M n="24" v="0.000915"/>
<C i="87" s="759" l="0" v="0x16a9a">
<M n="24" v="0.000915"/>
<PF i="88" s="760" l="0" lm="756" f="757" n="760">
<M n="24" v="0.000915"/>
<C i="89" s="761" l="0" v="0xedde">
<M n="24" v="0.000915"/>
<PF i="90" s="762" l="0" lm="756" f="757" n="762">
<M n="24" v="0.000915"/>
<C i="91" s="763" l="0" v="0xa08f">
<M n="24" v="0.000915"/>
<PF i="92" s="764" l="0" lm="756" f="757" n="764">
<M n="24" v="0.000915"/><M n="25" v="0.000915"/>
<S i="93" s="765" l="0" it="253">
<M n="24" v="0.000915"/><M n="25" v="0.000915"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<C i="94" s="887" l="0" v="0x43d2">
<M n="24" v="0.00499"/>
<PF i="95" s="909" l="0" lm="901" f="902" n="909">
<M n="24" v="0.00499"/><M n="25" v="0.00499"/>
<S i="96" s="910" l="0" it="149">
<M n="24" v="0.00499"/><M n="25" v="0.00499"/>
</S>
</PF>
</C>
<S i="97" s="887" l="0" it="135">
<M n="24" v="0.018953"/><M n="25" v="0.018953"/>
</S>
</PF>
</C>
<C i="98" s="783" l="0" v="0x285b4">
<M n="24" v="0.001995"/>
<PF i="99" s="892" l="0" lm="888" f="889" n="892">
<M n="24" v="0.001995"/>
<C i="100" s="893" l="0" v="0x1544b">
<M n="24" v="0.001995"/>
<PF i="101" s="894" l="0" lm="888" f="889" n="894">
<M n="24" v="0.001995"/><M n="25" v="0.001995"/>
<S i="102" s="895" l="0" it="255">
<M n="24" v="0.001995"/><M n="25" v="0.001995"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<S i="103" s="684" l="0" it="141">
<M n="24" v="0.003991"/><M n="25" v="0.003991"/>
</S>
</PF>
</C>
</PF>
</C>
<C i="104" s="505" l="767" v="0x402c5c">
<M n="24" v="0.003887"/>
<PF i="105" s="681" l="0" lm="673" f="674" n="681">
<M n="24" v="0.003887"/>
<C i="106" s="682" l="0" v="0x8dca2">
<M n="24" v="0.003887"/>
<PF i="107" s="683" l="0" lm="673" f="674" n="683">
<M n="24" v="0.003887"/>
<C i="108" s="684" l="0" v="0x4a715">
<M n="24" v="0.003887"/>
<PF i="109" s="746" l="0" lm="731" f="735" n="746">
<M n="24" v="0.003887"/><M n="25" v="0.003887"/>
<S i="110" s="747" l="0" it="93">
<M n="24" v="0.003887"/><M n="25" v="0.003887"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<Pr i="111" s="509" l="758" lm="2" f="3" n="509" a="1">
<M n="24" v="0.964936"/>
<Pr i="112" s="510" l="659" lm="2" f="3" n="510" a="1">
<M n="24" v="0.964936"/>
<C i="113" s="519" l="667" v="0x402c07">
<M n="24" v="0.960969"/>
<PF i="114" s="695" l="165" lm="693" f="694" n="695">
<M n="24" v="0.931024"/>
<C i="115" s="696" l="168" v="0xd93f">
<M n="24" v="0.912027"/>
<PF i="116" s="64" l="667" lm="2" f="3" n="64">
<M n="24" v="0.912027"/><M n="25" v="0.912027"/>
<S i="117" s="65" l="667" it="111"/>
<L i="118" s="69" l="668" f="3" v="0x40183a">
<M n="24" v="0.912027"/><M n="25" v="0.912027"/>
<S i="119" s="70" l="668">
<M n="24" v="0.912027"/><M n="25" v="0.912027"/>
</S>
</L>
</PF>
</C>