<?xml version="1.0"?>
<!DOCTYPE HPCToolkitExperiment [
<!-- ******************************************************************** -->
<!-- HPCToolkit Experiment DTD						  -->
<!-- Version 2.2							  -->
<!-- ******************************************************************** -->
<!ELEMENT HPCToolkitExperiment (Header, (SecCallPathProfile|SecFlatProfile)*)>
<!ATTLIST HPCToolkitExperiment
	  version CDATA #REQUIRED>

  <!-- ****************************************************************** -->

  <!-- Info/NV: flexible name-value pairs: (n)ame; (t)ype; (v)alue -->
  <!ELEMENT Info (NV*)>
  <!ATTLIST Info
	    n CDATA #IMPLIED>
  <!ELEMENT NV EMPTY>
  <!ATTLIST NV
	    n CDATA #REQUIRED
	    t CDATA #IMPLIED
	    v CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Header								  -->
  <!-- ****************************************************************** -->
  <!ELEMENT Header (Info*)>
  <!ATTLIST Header
	    n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section Header							  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecHeader (MetricTable?, MetricDBTable?, TraceDBTable?, LoadModuleTable?, FileTable?, ProcedureTable?, Info*)>

    <!-- MetricTable: -->
    <!ELEMENT MetricTable (Metric)*>

    <!-- Metric: (i)d; (n)ame -->
    <!--   o: metric sequence order (hpcrun metric order) -->
    <!--   md: metric description -->
    <!--   mp: metric parent ID   -->
    <!--   es: number of samples    (perf_events only) -->
    <!--   em: event multiplexed    (perf_events only) -->
    <!--   ep: average event period (perf_events only) -->
    <!--   (v)alue-type: transient type of values -->
    <!--   (t)ype: persistent type of metric      -->
    <!--   show: metric visibility type. Possible values: -->
    <!--        0: hidden -->
    <!--        1: shown  -->
    <!--        2: show inclusive metric only -->
    <!--        3: show exclusive metric only -->
    <!--        4: invisible, do not show at all -->
    <!--   show-percent: whether to show the percent (1) or not (0)  -->
    <!--   partner: the exclusive or inclusive partner ID of this metric -->
    <!--   fmt: format; show; -->
    <!ELEMENT Metric (MetricFormula*, Info?)>
    <!ATTLIST Metric
	      i            CDATA #REQUIRED
	      o	           CDATA #IMPLIED
	      n            CDATA #REQUIRED
	      md           CDATA #IMPLIED
	      mp           CDATA #IMPLIED
	      es           CDATA #IMPLIED
	      em           CDATA #IMPLIED
	      ep           CDATA #IMPLIED
	      v            (raw|final|derived-incr|derived) "raw"
	      t            (inclusive|exclusive|nil) "nil"
	      partner      CDATA #IMPLIED
	      fmt          CDATA #IMPLIED
	      show         (1|0|2|3|4) "1"
	      show-percent (1|0) "1">

    <!-- MetricFormula represents derived metrics: (t)ype; (frm): formula -->
    <!ELEMENT MetricFormula (Info?)>
    <!ATTLIST MetricFormula
	      t   (combine|finalize|view) "finalize"
	      i   CDATA #IMPLIED
	      frm CDATA #REQUIRED>

    <!-- Metric data, used in sections: (n)ame [from Metric]; (v)alue -->
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	      n CDATA #REQUIRED
	      v CDATA #REQUIRED>

    <!-- MetricDBTable: -->
    <!ELEMENT MetricDBTable (MetricDB)*>

    <!-- MetricDB: (i)d; (n)ame -->
    <!--   (t)ype: persistent type of metric -->
    <!--   db-glob:        file glob describing files in metric db -->
    <!--   db-id:          id within metric db -->
    <!--   db-num-metrics: number of metrics in db -->
    <!--   db-header-sz:   size (in bytes) of a db file header -->
    <!ELEMENT MetricDB EMPTY>
    <!ATTLIST MetricDB
	      i              CDATA #REQUIRED
	      n              CDATA #REQUIRED
	      t              (inclusive|exclusive|nil) "nil"
	      partner        CDATA #IMPLIED
	      db-glob        CDATA #IMPLIED
	      db-id          CDATA #IMPLIED
	      db-num-metrics CDATA #IMPLIED
	      db-header-sz   CDATA #IMPLIED>

    <!-- TraceDBTable: -->
    <!ELEMENT TraceDBTable (TraceDB)>

    <!-- TraceDB: (i)d -->
    <!--   u: unit time of the trace (ms, ns, ..) -->
    <!--   db-min-time: min beginning time stamp (global) -->
    <!--   db-max-time: max ending time stamp (global) -->
    <!ELEMENT TraceDB EMPTY>
    <!ATTLIST TraceDB
	      i            CDATA #REQUIRED
	      u            CDATA #IMPLIED
	      db-glob      CDATA #IMPLIED
	      db-min-time  CDATA #IMPLIED
	      db-max-time  CDATA #IMPLIED
	      db-header-sz CDATA #IMPLIED>

    <!-- LoadModuleTable assigns a short name to a load module -->
    <!ELEMENT LoadModuleTable (LoadModule)*>

    <!ELEMENT LoadModule (Info?)>
    <!ATTLIST LoadModule
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- FileTable assigns a short name to a file -->
    <!ELEMENT FileTable (File)*>

    <!ELEMENT File (Info?)>
    <!ATTLIST File
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- ProcedureTable assigns a short name to a procedure -->
    <!ELEMENT ProcedureTable (Procedure)*>

    <!-- Dictionary for procedure: (i)d, (n)ame, (f)eature and (v)alue of the address -->
    <!-- Possible value of f: -->
    <!-- 0: normal procedure -->
    <!-- 1: place holder, do not add anything -->
    <!-- 2: root-type, has to be shown in a separate view -->
    <!-- 3: invisible in hpcviewer, but visible in hpctraceviewer  -->
    <!ELEMENT Procedure (Info?)>
    <!ATTLIST Procedure
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED
	      f CDATA #IMPLIED
	      v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Call path profile					  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecCallPathProfile (SecHeader, SecCallPathProfileData)>
  <!ATTLIST SecCallPathProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecCallPathProfileData (PF|M)*>
      <!-- Procedure frame -->
      <!--   (i)d: unique identifier for cross referencing -->
      <!--   (s)tatic scope id -->
      <!--   (n)ame: a string or an id in ProcedureTable -->
      <!--   (lm) load module: a string or an id in LoadModuleTable -->
      <!--   (f)ile name: a string or an id in LoadModuleTable -->
      <!--   (l)ine range: "beg-end" (inclusive range) -->
      <!--   (a)lien: whether frame is alien to enclosing P -->
      <!--   (str)uct: hpcstruct node id -->
      <!--   (v)ma-range-set: "{[beg-end), [beg-end)...}" -->
      <!ELEMENT PF (PF|Pr|L|C|S|M)*>
      <!ATTLIST PF
		i  CDATA #IMPLIED
		s  CDATA #IMPLIED
		n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Procedure (static): GOAL: replace with 'P' -->
      <!ELEMENT Pr (Pr|L|C|S|M)*>
      <!ATTLIST Pr
                i  CDATA #IMPLIED
		s  CDATA #IMPLIED
                n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
                l  CDATA #IMPLIED
		a  (1|0) "0"
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Callsite (a special StatementRange) -->
      <!ELEMENT C (PF|M)*>
      <!ATTLIST C
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Flat profile						  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecFlatProfile (SecHeader, SecFlatProfileData)>
  <!ATTLIST SecFlatProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecFlatProfileData (LM|M)*>
      <!-- Load module: (i)d; (n)ame; (v)ma-range-set -->
      <!ELEMENT LM (F|P|M)*>
      <!ATTLIST LM
                i CDATA #IMPLIED
                n CDATA #REQUIRED
		v CDATA #IMPLIED>
      <!-- File -->
      <!ELEMENT F (P|L|S|M)*>
      <!ATTLIST F
                i CDATA #IMPLIED
                n CDATA #REQUIRED>
      <!-- Procedure (Note 1) -->
      <!ELEMENT P (P|A|L|S|C|M)*>
      <!ATTLIST P
                i CDATA #IMPLIED
                n CDATA #REQUIRED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Alien (Note 1) -->
      <!ELEMENT A (A|L|S|C|M)*>
      <!ATTLIST A
                i CDATA #IMPLIED
                f CDATA #IMPLIED
                n CDATA #IMPLIED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Loop (Note 1,2) -->
      <!ELEMENT L (A|Pr|L|S|C|M)*>
      <!ATTLIST L
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
	        f CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Statement (Note 2) -->
      <!--   (it): trace record identifier -->
      <!ELEMENT S (S|M)*>
      <!ATTLIST S
		i  CDATA #IMPLIED
		it CDATA #IMPLIED
		s  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Note 1: Contained Cs may not contain PFs -->
      <!-- Note 2: The 's' attribute is not used for flat profiles -->
]>
<HPCToolkitExperiment version="2.2">
<Header n="miniapp">
  <Info/>
</Header>
<SecCallPathProfile i="0" n="miniapp">
<SecHeader>
  <MetricTable>
    <Metric i="24" n="CPUTIME (sec):Sum (I)" o="0" v="derived-incr" md="CPUTIME (sec)" em="0" es="0" ep="0" t="inclusive" partner="25" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($24, $24)"/>
      <MetricFormula t="finalize" frm="$24"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="25" n="CPUTIME (sec):Sum (E)" o="-1" v="derived-incr" md="CPUTIME (sec)" em="0" es="0" ep="0" t="exclusive" partner="24" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($25, $25)"/>
      <MetricFormula t="finalize" frm="$25"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
  </MetricTable>
  <MetricDBTable>
  </MetricDBTable>
  <TraceDBTable>
    <TraceDB i="0" u="1000000000" db-glob="*.hpctrace" db-min-time="1596577185757424000" db-max-time="1596577186645304000" db-header-sz="32"/>
  </TraceDBTable>
  <LoadModuleTable>
    <LoadModule i="2" n="/home/u10/ianbertolacci/testcode/HPCToolkit-Testing-Miniapp/mpi_omp/miniapp"/>
    <LoadModule i="653" n="/opt/ohpc/pub/apps/hpctoolkit/2020.06/linux-centos7-zen/gcc-8.3.0/hpctoolkit-2020.06.12-eihbyb4brvhwsp2znuoxozo7uwus7y4n/lib/hpctoolkit/libhpcrun.so.0.0.0"/>
    <LoadModule i="657" n="/opt/ohpc/pub/apps/hpctoolkit/2020.06/linux-centos7-zen/gcc-8.3.0/hpctoolkit-2020.06.12-eihbyb4brvhwsp2znuoxozo7uwus7y4n/lib/hpctoolkit/ext-libs/libmonitor.so.0.0.0"/>
    <LoadModule i="669" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/libmpi.so.40.10.4"/>
    <LoadModule i="697" n="/opt/ohpc/pub/compiler/gcc/8.3.0/lib64/libgomp.so.1.0.0"/>
    <LoadModule i="745" n="/usr/lib64/libpthread-2.17.so"/>
    <LoadModule i="749" n="/usr/lib64/libc-2.17.so"/>
    <LoadModule i="772" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/libopen-rte.so.40.10.4"/>
    <LoadModule i="780" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/libopen-pal.so.40.10.4"/>
    <LoadModule i="811" n="/usr/lib64/libevent-2.0.so.5.1.9"/>
    <LoadModule i="823" n="[vdso]"/>
    <LoadModule i="827" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_ess_pmi.so"/>
    <LoadModule i="833" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_pmix_ext2x.so"/>
    <LoadModule i="839" n="/opt/ohpc/admin/pmix/lib/libpmix.so.2.1.22"/>
    <LoadModule i="869" n="/opt/ohpc/admin/pmix/lib/pmix/mca_gds_hash.so"/>
    <LoadModule i="873" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_btl_vader.so"/>
    <LoadModule i="880" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_btl_openib.so"/>
    <LoadModule i="891" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_pml_ob1.so"/>
  </LoadModuleTable>
  <FileTable>
    <File i="3" n="./src/home/u10/ianbertolacci/testcode/HPCToolkit-Testing-Miniapp/mpi_omp/miniapp.c"/>
    <File i="654" n="&lt;unknown file&gt; [libhpcrun.so.0.0.0]"/>
    <File i="658" n="&lt;unknown file&gt; [libmonitor.so.0.0.0]"/>
    <File i="670" n="&lt;unknown file&gt; [libmpi.so.40.10.4]"/>
    <File i="698" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/parallel.c"/>
    <File i="737" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/libgomp.h"/>
    <File i="705" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/team.c"/>
    <File i="708" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/alloc.c"/>
    <File i="715" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/task.c"/>
    <File i="723" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/linux/bar.c"/>
    <File i="727" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/linux/x86/futex.h"/>
    <File i="729" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/linux/bar.h"/>
    <File i="746" n="pthread_mutexattr_init.c"/>
    <File i="750" n="isoc99_fscanf.c"/>
    <File i="761" n="&lt;unknown file&gt; [libc-2.17.so]"/>
    <File i="773" n="&lt;unknown file&gt; [libopen-rte.so.40.10.4]"/>
    <File i="781" n="&lt;unknown file&gt; [libopen-pal.so.40.10.4]"/>
    <File i="792" n="opal_finalize.c"/>
    <File i="812" n="&lt;unknown file&gt; [libevent-2.0.so.5.1.9]"/>
    <File i="824" n="&lt;unknown file&gt; [vdso]"/>
    <File i="828" n="crtstuff.c"/>
    <File i="834" n="&lt;unknown file&gt; [mca_pmix_ext2x.so]"/>
    <File i="840" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/client/pmix_client.c"/>
    <File i="863" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/class/pmix_object.h"/>
    <File i="846" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/runtime/pmix_progress_threads.c"/>
    <File i="866" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/util/hash.c"/>
    <File i="870" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/mca/gds/hash/gds_hash.c"/>
    <File i="874" n="&lt;unknown file&gt; [mca_btl_vader.so]"/>
    <File i="877" n="btl_vader_put.c"/>
    <File i="881" n="btl_openib_atomic.c"/>
    <File i="884" n="&lt;unknown file&gt; [mca_btl_openib.so]"/>
    <File i="892" n="&lt;unknown file&gt; [mca_pml_ob1.so]"/>
    <File i="895" n="pml_ob1_sendreq.c"/>
  </FileTable>
  <ProcedureTable>
    <Procedure i="64" n="in_place_stencilize_local_array._omp_fn.3" v="0x401770"/>
    <Procedure i="459" n="in_place_stencilize_distributed_array" v="0x402ac0"/>
    <Procedure i="509" n="" v="0"/>
    <Procedure i="510" n="in_place_stencilize_local_array" v="0"/>
    <Procedure i="71" n="sum_local_array._omp_fn.4" v="0x4018f0"/>
    <Procedure i="527" n="sum_distributed_array" v="0x402ed0"/>
    <Procedure i="548" n="sum_local_array" v="0"/>
    <Procedure i="4" n="main" v="0x401200"/>
    <Procedure i="37" n="program_finalize" v="0"/>
    <Procedure i="655" n="&lt;no activity&gt;" f="3" v="0"/>
    <Procedure i="659" n="&lt;program root&gt;" f="4" v="0"/>
    <Procedure i="665" n="MPI_Finalize" v="0"/>
    <Procedure i="667" n="&lt;thread root&gt;" f="4" v="0"/>
    <Procedure i="675" n="MPI_Isend" v="0"/>
    <Procedure i="677" n="MPI_Irecv" v="0"/>
    <Procedure i="679" n="PMPI_Wait" v="0"/>
    <Procedure i="681" n="ompi_request_default_wait" v="0"/>
    <Procedure i="683" n="PMPI_Gather" v="0"/>
    <Procedure i="685" n="ompi_coll_base_gather_intra_basic_linear" v="0"/>
    <Procedure i="687" n="ompi_mpi_finalize" v="0"/>
    <Procedure i="689" n="ompi_attr_finalize" v="0"/>
    <Procedure i="691" n="ompi_attr_free_predefined" v="0"/>
    <Procedure i="693" n="ompi_attr_free_keyval@plt" v="0"/>
    <Procedure i="695" n="opal_finalize_util@plt" v="0"/>
    <Procedure i="735" n="gomp_resolve_num_threads" v="0"/>
    <Procedure i="737" n="&lt;inline&gt;" v="0"/>
    <Procedure i="699" n="GOMP_parallel_end" v="0"/>
    <Procedure i="701" n="&lt;inline&gt;" v="0"/>
    <Procedure i="703" n="GOMP_parallel" v="0"/>
    <Procedure i="706" n="gomp_new_team" v="0"/>
    <Procedure i="740" n="&lt;inline&gt;" v="0"/>
    <Procedure i="711" n="gomp_team_start" v="0"/>
    <Procedure i="721" n="gomp_team_end" v="0"/>
    <Procedure i="709" n="gomp_malloc" v="0"/>
    <Procedure i="716" n="gomp_init_task" v="0"/>
    <Procedure i="718" n="&lt;inline&gt;" v="0"/>
    <Procedure i="724" n="gomp_team_barrier_wait_end" v="0"/>
    <Procedure i="727" n="&lt;inline&gt;" v="0"/>
    <Procedure i="730" n="gomp_barrier_wait_final_start" v="0"/>
    <Procedure i="747" n="__close_nocancel" v="0"/>
    <Procedure i="751" n="__GI___libc_malloc" v="0"/>
    <Procedure i="753" n="_int_malloc" v="0"/>
    <Procedure i="755" n="__GI_sched_yield" v="0"/>
    <Procedure i="757" n="__memcpy_ssse3" v="0"/>
    <Procedure i="759" n="__free" v="0"/>
    <Procedure i="764" n="__nanosleep_nocancel" v="0"/>
    <Procedure i="766" n="_int_free" v="0"/>
    <Procedure i="768" n="__epoll_wait_nocancel" v="0"/>
    <Procedure i="770" n="__GI___clock_gettime" v="0"/>
    <Procedure i="762" n="usleep" v="0"/>
    <Procedure i="776" n="orte_finalize" v="0"/>
    <Procedure i="778" n="orte_ess_base_app_finalize" v="0"/>
    <Procedure i="786" n="opal_progress" v="0"/>
    <Procedure i="788" n="opal_convertor_unpack" v="0"/>
    <Procedure i="790" n="mca_base_framework_close" v="0"/>
    <Procedure i="795" n="mca_base_components_close" v="0"/>
    <Procedure i="797" n="mca_base_component_close" v="0"/>
    <Procedure i="799" n="opal_finalize_util" v="0"/>
    <Procedure i="801" n="mca_base_var_group_deregister" v="0"/>
    <Procedure i="803" n="mca_base_var_get" v="0"/>
    <Procedure i="805" n="mca_base_var_finalize" v="0"/>
    <Procedure i="807" n="mca_base_var_group_finalize" v="0"/>
    <Procedure i="793" n="mca_btl_base_close" v="0"/>
    <Procedure i="809" n="mca_base_var_group_destructor" v="0"/>
    <Procedure i="813" n="event_base_free" v="0"/>
    <Procedure i="815" n="_event_strlcpy" v="0"/>
    <Procedure i="817" n="evsig_dealloc" v="0"/>
    <Procedure i="819" n="event_base_loop" v="0"/>
    <Procedure i="821" n="&lt;unknown procedure&gt; 0xce9c [libevent-2.0.so.5.1.9]" v="0"/>
    <Procedure i="825" n="__vdso_clock_gettime" v="0"/>
    <Procedure i="831" n="rte_finalize" v="0"/>
    <Procedure i="837" n="ext2x_client_finalize" v="0"/>
    <Procedure i="853" n="PMIx_Finalize" v="0"/>
    <Procedure i="862" n="_putfn" v="0"/>
    <Procedure i="863" n="&lt;inline&gt;" v="0"/>
    <Procedure i="858" n="tracker_destructor" v="0"/>
    <Procedure i="860" n="progress_engine" v="0"/>
    <Procedure i="855" n="pmix_progress_thread_stop" v="0"/>
    <Procedure i="856" n="&lt;inline&gt;" v="0"/>
    <Procedure i="867" n="pmix_hash_store" v="0"/>
    <Procedure i="871" n="hash_store" v="0"/>
    <Procedure i="875" n="mca_btl_vader_sendi" v="0"/>
    <Procedure i="878" n="mca_btl_vader_component_progress" v="0"/>
    <Procedure i="882" n="btl_openib_component_close" v="0"/>
    <Procedure i="887" n="device_values_destructor" v="0"/>
    <Procedure i="885" n="opal_btl_openib_ini_finalize" v="0"/>
    <Procedure i="889" n="free@plt" v="0"/>
    <Procedure i="893" n="mca_pml_ob1_isend" v="0"/>
    <Procedure i="898" n="mca_pml_ob1_irecv" v="0"/>
    <Procedure i="900" n="mca_pml_ob1_recv_req_start" v="0"/>
    <Procedure i="904" n="mca_pml_ob1_recv_frag_callback_match" v="0"/>
    <Procedure i="910" n="mca_pml_ob1_recv" v="0"/>
    <Procedure i="912" n="mca_pml_ob1_recv_request_progress_match" v="0"/>
    <Procedure i="914" n="mca_pml_ob1_send" v="0"/>
    <Procedure i="896" n="mca_pml_ob1_send_inline.constprop.6" v="0"/>
    <Procedure i="902" n="mca_pml_ob1_recv_request_free" v="0"/>
    <Procedure i="906" n="match_one" v="0"/>
    <Procedure i="908" n="append_frag_to_list" v="0"/>
  </ProcedureTable>
  <Info/>
</SecHeader>
<SecCallPathProfileData>
<M n="24" v="2.7021"/>
<PF i="2" s="655" l="0" lm="653" f="654" n="655">
<S i="3" s="656" l="0" it="267"/>
</PF>
<PF i="4" s="659" l="0" lm="657" f="658" n="659">
<M n="24" v="1.9864"/>
<C i="5" s="660" l="0" v="0xd76a">
<M n="24" v="1.9864"/>
<PF i="6" s="4" l="858" lm="2" f="3" n="4">
<M n="24" v="1.9864"/>
<L i="7" s="26" l="879" f="3" v="0x401280">
<M n="24" v="1.92742"/>
<C i="8" s="33" l="881" v="0x40128a">
<M n="24" v="1.30028"/>
<PF i="9" s="459" l="695" lm="2" f="3" n="459">
<M n="24" v="1.30028"/><M n="25" v="0.004994"/>
<S i="10" s="460" l="695" it="319"/>
<S i="11" s="483" l="766">
<M n="24" v="0.004994"/><M n="25" v="0.004994"/>
</S>
<C i="12" s="498" l="721" v="0x402dab">
<M n="24" v="0.012972"/>
<PF i="13" s="675" l="0" lm="669" f="670" n="675">
<M n="24" v="0.012972"/><M n="25" v="0.002995"/>
<C i="14" s="676" l="0" v="0x7af25">
<M n="24" v="0.009977"/>
<PF i="15" s="893" l="0" lm="891" f="892" n="893">
<M n="24" v="0.009977"/>
<C i="16" s="894" l="0" v="0xb8e7">
<M n="24" v="0.009977"/>
<PF i="17" s="896" l="0" lm="891" f="895" n="896">
<M n="24" v="0.009977"/><M n="25" v="0.006989"/>
<C i="18" s="897" l="0" v="0xad68">
<M n="24" v="0.002988"/>
<PF i="19" s="875" l="0" lm="873" f="874" n="875">
<M n="24" v="0.002988"/><M n="25" v="0.000994"/>
<C i="20" s="876" l="0" v="0x574d">
<M n="24" v="0.001994"/>
<PF i="21" s="757" l="0" lm="749" f="750" n="757">
<M n="24" v="0.001994"/><M n="25" v="0.001994"/>
<S i="22" s="758" l="0" it="141">
<M n="24" v="0.001994"/><M n="25" v="0.001994"/>
</S>
</PF>
</C>
<S i="23" s="876" l="0" it="139">
<M n="24" v="0.000994"/><M n="25" v="0.000994"/>
</S>
</PF>
</C>
<S i="24" s="897" l="0" it="193">
<M n="24" v="0.006989"/><M n="25" v="0.006989"/>
</S>
</PF>
</C>
</PF>
</C>
<S i="25" s="676" l="0" it="307">
<M n="24" v="0.002995"/><M n="25" v="0.002995"/>
</S>
</PF>
</C>
<C i="26" s="499" l="728" v="0x402de8">
<M n="24" v="0.017882"/>
<PF i="27" s="677" l="0" lm="669" f="670" n="677">
<M n="24" v="0.017882"/>
<C i="28" s="678" l="0" v="0x7a8e5">
<M n="24" v="0.017882"/>
<PF i="29" s="898" l="0" lm="891" f="892" n="898">
<M n="24" v="0.017882"/><M n="25" v="0.012893"/>
<C i="30" s="899" l="0" v="0x8d67">
<M n="24" v="0.004989"/>
<PF i="31" s="900" l="0" lm="891" f="892" n="900">
<M n="24" v="0.004989"/><M n="25" v="0.004989"/>
<S i="32" s="901" l="0" it="309">
<M n="24" v="0.004989"/><M n="25" v="0.004989"/>
</S>
</PF>
</C>
<S i="33" s="899" l="0" it="289">
<M n="24" v="0.012893"/><M n="25" v="0.012893"/>
</S>
</PF>
</C>
</PF>
</C>
<C i="34" s="502" l="739" v="0x402b6e">
<M n="24" v="0.008989"/>
<PF i="35" s="675" l="0" lm="669" f="670" n="675">
<M n="24" v="0.008989"/><M n="25" v="0.005995"/>
<C i="36" s="676" l="0" v="0x7af25">
<M n="24" v="0.002994"/>
<PF i="37" s="893" l="0" lm="891" f="892" n="893">
<M n="24" v="0.002994"/>
<C i="38" s="894" l="0" v="0xb8e7">
<M n="24" v="0.002994"/>
<PF i="39" s="896" l="0" lm="891" f="895" n="896">
<M n="24" v="0.002994"/>
<C i="40" s="897" l="0" v="0xad68">
<M n="24" v="0.002994"/>
<PF i="41" s="875" l="0" lm="873" f="874" n="875">
<M n="24" v="0.002994"/><M n="25" v="0.002994"/>
<S i="42" s="876" l="0" it="255">
<M n="24" v="0.002994"/><M n="25" v="0.002994"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<S i="43" s="676" l="0" it="221">
<M n="24" v="0.005995"/><M n="25" v="0.005995"/>
</S>
</PF>
</C>
<C i="44" s="503" l="746" v="0x402ba9">
<M n="24" v="0.001996"/>
<PF i="45" s="677" l="0" lm="669" f="670" n="677">
<M n="24" v="0.001996"/>
<C i="46" s="678" l="0" v="0x7a8e5">
<M n="24" v="0.001996"/>
<PF i="47" s="898" l="0" lm="891" f="892" n="898">
<M n="24" v="0.001996"/>
<C i="48" s="899" l="0" v="0x8d67">
<M n="24" v="0.001996"/>
<PF i="49" s="900" l="0" lm="891" f="892" n="900">
<M n="24" v="0.001996"/><M n="25" v="0.001996"/>
<S i="50" s="901" l="0" it="173">
<M n="24" v="0.001996"/><M n="25" v="0.001996"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<C i="51" s="504" l="767" v="0x402c4a">
<M n="24" v="0.277012"/>
<PF i="52" s="679" l="0" lm="669" f="670" n="679">
<M n="24" v="0.277012"/><M n="25" v="0.010988"/>
<C i="53" s="680" l="0" v="0x8dca2">
<M n="24" v="0.266024"/>
<PF i="54" s="681" l="0" lm="669" f="670" n="681">
<M n="24" v="0.266024"/><M n="25" v="0.013944"/>
<C i="55" s="682" l="0" v="0x4a6f1">
<M n="24" v="0.000995"/>
<PF i="56" s="902" l="0" lm="891" f="895" n="902">
<M n="24" v="0.000995"/><M n="25" v="0.000995"/>
<S i="57" s="903" l="0" it="143">
<M n="24" v="0.000995"/><M n="25" v="0.000995"/>
</S>
</PF>
</C>
<C i="58" s="682" l="0" v="0x4a715">
<M n="24" v="0.251085"/>
<PF i="59" s="755" l="0" lm="749" f="750" n="755">
<M n="24" v="0.165455"/><M n="25" v="0.165455"/>
<S i="60" s="756" l="0" it="77">
<M n="24" v="0.165455"/><M n="25" v="0.165455"/>
</S>
</PF>
<PF i="61" s="786" l="0" lm="780" f="781" n="786">
<M n="24" v="0.08563"/><M n="25" v="0.013934"/>
<C i="62" s="787" l="0" v="0x2856c">
<M n="24" v="0.071696"/>
<PF i="63" s="878" l="0" lm="873" f="877" n="878">
<M n="24" v="0.071696"/><M n="25" v="0.054859"/>
<C i="64" s="879" l="0" v="0x43d2">
<M n="24" v="0.016837"/>
<PF i="65" s="904" l="0" lm="891" f="892" n="904">
<M n="24" v="0.016837"/><M n="25" v="0.01193"/>
<C i="66" s="905" l="0" v="0x1111e">
<M n="24" v="0.002948"/>
<PF i="67" s="906" l="0" lm="891" f="895" n="906">
<M n="24" v="0.002948"/>
<C i="68" s="907" l="0" v="0xf855">
<M n="24" v="0.002948"/>
<PF i="69" s="908" l="0" lm="891" f="895" n="908">
<M n="24" v="0.002948"/><M n="25" v="0.002948"/>
<S i="70" s="909" l="0" it="137">
<M n="24" v="0.002948"/><M n="25" v="0.002948"/>
</S>
</PF>
</C>
</PF>
</C>
<C i="71" s="905" l="0" v="0x114cb">
<M n="24" v="0.001959"/>
<PF i="72" s="788" l="0" lm="780" f="781" n="788">
<M n="24" v="0.001959"/>
<C i="73" s="789" l="0" v="0x389b6">
<M n="24" v="0.001959"/>
<PF i="74" s="757" l="0" lm="749" f="750" n="757">
<M n="24" v="0.001959"/><M n="25" v="0.001959"/>
<S i="75" s="758" l="0" it="187">
<M n="24" v="0.001959"/><M n="25" v="0.001959"/>
</S>
</PF>
</C>
</PF>
</C>
<S i="76" s="905" l="0" it="201">
<M n="24" v="0.01193"/><M n="25" v="0.01193"/>
</S>
</PF>
</C>
<S i="77" s="879" l="0" it="287">
<M n="24" v="0.054859"/><M n="25" v="0.054859"/>
</S>
</PF>
</C>
<S i="78" s="787" l="0" it="111">
<M n="24" v="0.013934"/><M n="25" v="0.013934"/>
</S>
</PF>
</C>
<S i="79" s="682" l="0" it="239">
<M n="24" v="0.013944"/><M n="25" v="0.013944"/>
</S>
</PF>
</C>
<S i="80" s="680" l="0" it="161">
<M n="24" v="0.010988"/><M n="25" v="0.010988"/>
</S>
</PF>
</C>
<Pr i="81" s="509" l="758" lm="2" f="3" n="509" a="1">
<M n="24" v="0.976435"/>
<Pr i="82" s="510" l="659" lm="2" f="3" n="510" a="1">
<M n="24" v="0.976435"/><M n="25" v="0.000995"/>
<S i="83" s="514" l="667">
<M n="24" v="0.000995"/><M n="25" v="0.000995"/>
</S>
<C i="84" s="518" l="659" v="0x402bc4">
<M n="24" v="0.002941"/>
<PF i="85" s="751" l="0" lm="749" f="750" n="751">
<M n="24" v="0.002941"/>
<C i="86" s="752" l="0" v="0x856fc">
<M n="24" v="0.002941"/>
<PF i="87" s="753" l="0" lm="749" f="750" n="753">
<M n="24" v="0.002941"/><M n="25" v="0.002941"/>
<S i="88" s="754" l="0" it="311">
<M n="24" v="0.002941"/><M n="25" v="0.002941"/>
</S>
</PF>
</C>
</PF>
</C>
<C i="89" s="519" l="667" v="0x402c07">
<M n="24" v="0.972499"/>
<PF i="90" s="699" l="131" lm="697" f="698" n="699">
<M n="24" v="0.006993"/><M n="25" v="0.006993"/>
<S i="91" s="700" l="131" it="317"/>
<Pr i="92" s="701" l="679" lm="697" f="737" n="701" a="1">
<M n="24" v="0.006993"/><M n="25" v="0.006993"/>
<S i="93" s="702" l="679">
<M n="24" v="0.006993"/><M n="25" v="0.006993"/>
</S>
</Pr>
</PF>
<PF i="94" s="703" l="165" lm="697" f="698" n="703">
<M n="24" v="0.932585"/>
<C i="95" s="704" l="167" v="0xd926">
<M n="24" v="0.00994"/>
<PF i="96" s="706" l="161" lm="697" f="705" n="706">
<M n="24" v="0.00994"/>
<C i="97" s="707" l="170" v="0x162d8">
<M n="24" v="0.00994"/>
<PF i="98" s="709" l="36" lm="697" f="708" n="709">
<M n="24" v="0.00994"/>
<C i="99" s="710" l="37" v="0x9679">
<M n="24" v="0.00994"/>
<PF i="100" s="751" l="0" lm="749" f="750" n="751">
<M n="24" v="0.00994"/><M n="25" v="0.006946"/>
<C i="101" s="752" l="0" v="0x856fc">
<M n="24" v="0.002994"/>
<PF i="102" s="753" l="0" lm="749" f="750" n="753">
<M n="24" v="0.002994"/><M n="25" v="0.002994"/>
<S i="103" s="754" l="0" it="305">
<M n="24" v="0.002994"/><M n="25" v="0.002994"/>
</S>
</PF>
</C>
<S i="104" s="752" l="0" it="117">
<M n="24" v="0.006946"/><M n="25" v="0.006946"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<C i="105" s="704" l="167" v="0xd93a">
<M n="24" v="0.007988"/>
<PF i="106" s="711" l="301" lm="697" f="705" n="711">
<M n="24" v="0.007988"/><M n="25" v="0.006995"/>
<S i="107" s="712" l="301" it="167"/>
<S i="108" s="713" l="320">
<M n="24" v="0.006995"/><M n="25" v="0.006995"/>
</S>
<C i="109" s="714" l="352" v="0x16626">
<M n="24" v="0.000993"/>
<PF i="110" s="716" l="77" lm="697" f="715" n="716">
<M n="24" v="0.000993"/><M n="25" v="0.000993"/>
<S i="111" s="717" l="77" it="165"/>
<Pr i="112" s="718" l="76" lm="697" f="715" n="718" a="1">
<M n="24" v="0.000993"/><M n="25" v="0.000993"/>
<S i="113" s="719" l="76">
<M n="24" v="0.000993"/><M n="25" v="0.000993"/>
</S>
</Pr>
</PF>
</C>
</PF>
</C>
<C i="114" s="720" l="168" v="0xd93f">
<M n="24" v="0.914657"/>
<PF i="115" s="64" l="667" lm="2" f="3" n="64">
<M n="24" v="0.914657"/><M n="25" v="0.914657"/>
<S i="116" s="65" l="667" it="123"/>
<L i="117" s="69" l="668" f="3" v="0x40183a">
<M n="24" v="0.914657"/><M n="25" v="0.914657"/>
<S i="118" s="70" l="668">
<M n="24" v="0.914657"/><M n="25" v="0.914657"/>
</S>
</L>
</PF>
</C>
</PF>
<PF i="119" s="721" l="869" lm="697" f="705" n="721">
<M n="24" v="0.032921"/>
<C i="120" s="722" l="877" v="0x17689">
<M n="24" v="0.032921"/>
<PF i="121" s="724" l="82" lm="697" f="723" n="724">
<M n="24" v="0.029927"/><M n="25" v="0.029927"/>
<S i="122" s="725" l="82" it="155">
<M n="24" v="0.001993"/><M n="25" v="0.001993"/>
</S>
<S i="123" s="726" l="102">
<M n="24" v="0.004993"/><M n="25" v="0.004993"/>
</S>