<?xml version="1.0"?>
<!DOCTYPE HPCToolkitExperiment [
<!-- ******************************************************************** -->
<!-- HPCToolkit Experiment DTD						  -->
<!-- Version 2.2							  -->
<!-- ******************************************************************** -->
<!ELEMENT HPCToolkitExperiment (Header, (SecCallPathProfile|SecFlatProfile)*)>
<!ATTLIST HPCToolkitExperiment
	  version CDATA #REQUIRED>

  <!-- ****************************************************************** -->

  <!-- Info/NV: flexible name-value pairs: (n)ame; (t)ype; (v)alue -->
  <!ELEMENT Info (NV*)>
  <!ATTLIST Info
	    n CDATA #IMPLIED>
  <!ELEMENT NV EMPTY>
  <!ATTLIST NV
	    n CDATA #REQUIRED
	    t CDATA #IMPLIED
	    v CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Header								  -->
  <!-- ****************************************************************** -->
  <!ELEMENT Header (Info*)>
  <!ATTLIST Header
	    n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section Header							  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecHeader (MetricTable?, MetricDBTable?, TraceDBTable?, LoadModuleTable?, FileTable?, ProcedureTable?, Info*)>

    <!-- MetricTable: -->
    <!ELEMENT MetricTable (Metric)*>

    <!-- Metric: (i)d; (n)ame -->
    <!--   o: metric sequence order (hpcrun metric order) -->
    <!--   md: metric description -->
    <!--   mp: metric parent ID   -->
    <!--   es: number of samples    (perf_events only) -->
    <!--   em: event multiplexed    (perf_events only) -->
    <!--   ep: average event period (perf_events only) -->
    <!--   (v)alue-type: transient type of values -->
    <!--   (t)ype: persistent type of metric      -->
    <!--   show: metric visibility type. Possible values: -->
    <!--        0: hidden -->
    <!--        1: shown  -->
    <!--        2: show inclusive metric only -->
    <!--        3: show exclusive metric only -->
    <!--        4: invisible, do not show at all -->
    <!--   show-percent: whether to show the percent (1) or not (0)  -->
    <!--   partner: the exclusive or inclusive partner ID of this metric -->
    <!--   fmt: format; show; -->
    <!ELEMENT Metric (MetricFormula*, Info?)>
    <!ATTLIST Metric
	      i            CDATA #REQUIRED
	      o	           CDATA #IMPLIED
	      n            CDATA #REQUIRED
	      md           CDATA #IMPLIED
	      mp           CDATA #IMPLIED
	      es           CDATA #IMPLIED
	      em           CDATA #IMPLIED
	      ep           CDATA #IMPLIED
	      v            (raw|final|derived-incr|derived) "raw"
	      t            (inclusive|exclusive|nil) "nil"
	      partner      CDATA #IMPLIED
	      fmt          CDATA #IMPLIED
	      show         (1|0|2|3|4) "1"
	      show-percent (1|0) "1">

    <!-- MetricFormula represents derived metrics: (t)ype; (frm): formula -->
    <!ELEMENT MetricFormula (Info?)>
    <!ATTLIST MetricFormula
	      t   (combine|finalize|view) "finalize"
	      i   CDATA #IMPLIED
	      frm CDATA #REQUIRED>

    <!-- Metric data, used in sections: (n)ame [from Metric]; (v)alue -->
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	      n CDATA #REQUIRED
	      v CDATA #REQUIRED>

    <!-- MetricDBTable: -->
    <!ELEMENT MetricDBTable (MetricDB)*>

    <!-- MetricDB: (i)d; (n)ame -->
    <!--   (t)ype: persistent type of metric -->
    <!--   db-glob:        file glob describing files in metric db -->
    <!--   db-id:          id within metric db -->
    <!--   db-num-metrics: number of metrics in db -->
    <!--   db-header-sz:   size (in bytes) of a db file header -->
    <!ELEMENT MetricDB EMPTY>
    <!ATTLIST MetricDB
	      i              CDATA #REQUIRED
	      n              CDATA #REQUIRED
	      t              (inclusive|exclusive|nil) "nil"
	      partner        CDATA #IMPLIED
	      db-glob        CDATA #IMPLIED
	      db-id          CDATA #IMPLIED
	      db-num-metrics CDATA #IMPLIED
	      db-header-sz   CDATA #IMPLIED>

    <!-- TraceDBTable: -->
    <!ELEMENT TraceDBTable (TraceDB)>

    <!-- TraceDB: (i)d -->
    <!--   u: unit time of the trace (ms, ns, ..) -->
    <!--   db-min-time: min beginning time stamp (global) -->
    <!--   db-max-time: max ending time stamp (global) -->
    <!ELEMENT TraceDB EMPTY>
    <!ATTLIST TraceDB
	      i            CDATA #REQUIRED
	      u            CDATA #IMPLIED
	      db-glob      CDATA #IMPLIED
	      db-min-time  CDATA #IMPLIED
	      db-max-time  CDATA #IMPLIED
	      db-header-sz CDATA #IMPLIED>

    <!-- LoadModuleTable assigns a short name to a load module -->
    <!ELEMENT LoadModuleTable (LoadModule)*>

    <!ELEMENT LoadModule (Info?)>
    <!ATTLIST LoadModule
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- FileTable assigns a short name to a file -->
    <!ELEMENT FileTable (File)*>

    <!ELEMENT File (Info?)>
    <!ATTLIST File
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- ProcedureTable assigns a short name to a procedure -->
    <!ELEMENT ProcedureTable (Procedure)*>

    <!-- Dictionary for procedure: (i)d, (n)ame, (f)eature and (v)alue of the address -->
    <!-- Possible value of f: -->
    <!-- 0: normal procedure -->
    <!-- 1: place holder, do not add anything -->
    <!-- 2: root-type, has to be shown in a separate view -->
    <!-- 3: invisible in hpcviewer, but visible in hpctraceviewer  -->
    <!ELEMENT Procedure (Info?)>
    <!ATTLIST Procedure
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED
	      f CDATA #IMPLIED
	      v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Call path profile					  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecCallPathProfile (SecHeader, SecCallPathProfileData)>
  <!ATTLIST SecCallPathProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecCallPathProfileData (PF|M)*>
      <!-- Procedure frame -->
      <!--   (i)d: unique identifier for cross referencing -->
      <!--   (s)tatic scope id -->
      <!--   (n)ame: a string or an id in ProcedureTable -->
      <!--   (lm) load module: a string or an id in LoadModuleTable -->
      <!--   (f)ile name: a string or an id in LoadModuleTable -->
      <!--   (l)ine range: "beg-end" (inclusive range) -->
      <!--   (a)lien: whether frame is alien to enclosing P -->
      <!--   (str)uct: hpcstruct node id -->
      <!--   (v)ma-range-set: "{[beg-end), [beg-end)...}" -->
      <!ELEMENT PF (PF|Pr|L|C|S|M)*>
      <!ATTLIST PF
		i  CDATA #IMPLIED
		s  CDATA #IMPLIED
		n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Procedure (static): GOAL: replace with 'P' -->
      <!ELEMENT Pr (Pr|L|C|S|M)*>
      <!ATTLIST Pr
                i  CDATA #IMPLIED
		s  CDATA #IMPLIED
                n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
                l  CDATA #IMPLIED
		a  (1|0) "0"
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Callsite (a special StatementRange) -->
      <!ELEMENT C (PF|M)*>
      <!ATTLIST C
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Flat profile						  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecFlatProfile (SecHeader, SecFlatProfileData)>
  <!ATTLIST SecFlatProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecFlatProfileData (LM|M)*>
      <!-- Load module: (i)d; (n)ame; (v)ma-range-set -->
      <!ELEMENT LM (F|P|M)*>
      <!ATTLIST LM
                i CDATA #IMPLIED
                n CDATA #REQUIRED
		v CDATA #IMPLIED>
      <!-- File -->
      <!ELEMENT F (P|L|S|M)*>
      <!ATTLIST F
                i CDATA #IMPLIED
                n CDATA #REQUIRED>
      <!-- Procedure (Note 1) -->
      <!ELEMENT P (P|A|L|S|C|M)*>
      <!ATTLIST P
                i CDATA #IMPLIED
                n CDATA #REQUIRED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Alien (Note 1) -->
      <!ELEMENT A (A|L|S|C|M)*>
      <!ATTLIST A
                i CDATA #IMPLIED
                f CDATA #IMPLIED
                n CDATA #IMPLIED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Loop (Note 1,2) -->
      <!ELEMENT L (A|Pr|L|S|C|M)*>
      <!ATTLIST L
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
	        f CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Statement (Note 2) -->
      <!--   (it): trace record identifier -->
      <!ELEMENT S (S|M)*>
      <!ATTLIST S
		i  CDATA #IMPLIED
		it CDATA #IMPLIED
		s  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Note 1: Contained Cs may not contain PFs -->
      <!-- Note 2: The 's' attribute is not used for flat profiles -->
]>
<HPCToolkitExperiment version="2.2">
<Header n="miniapp">
  <Info/>
</Header>
<SecCallPathProfile i="0" n="miniapp">
<SecHeader>
  <MetricTable>
    <Metric i="24" n="CPUTIME (sec):Sum (I)" o="0" v="derived-incr" md="CPUTIME (sec)" em="0" es="0" ep="0" t="inclusive" partner="25" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($24, $24)"/>
      <MetricFormula t="finalize" frm="$24"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="25" n="CPUTIME (sec):Sum (E)" o="-1" v="derived-incr" md="CPUTIME (sec)" em="0" es="0" ep="0" t="exclusive" partner="24" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($25, $25)"/>
      <MetricFormula t="finalize" frm="$25"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
  </MetricTable>
  <MetricDBTable>
  </MetricDBTable>
  <TraceDBTable>
    <TraceDB i="0" u="1000000000" db-glob="*.hpctrace" db-min-time="1596577088571425000" db-max-time="1596577090557300000" db-header-sz="32"/>
  </TraceDBTable>
  <LoadModuleTable>
    <LoadModule i="2" n="/home/u10/ianbertolacci/testcode/HPCToolkit-Testing-Miniapp/mpi_omp/miniapp"/>
    <LoadModule i="649" n="&lt;unknown load module&gt;"/>
    <LoadModule i="653" n="/opt/ohpc/pub/apps/hpctoolkit/2020.06/linux-centos7-zen/gcc-8.3.0/hpctoolkit-2020.06.12-eihbyb4brvhwsp2znuoxozo7uwus7y4n/lib/hpctoolkit/libhpcrun.so.0.0.0"/>
    <LoadModule i="657" n="/opt/ohpc/pub/apps/hpctoolkit/2020.06/linux-centos7-zen/gcc-8.3.0/hpctoolkit-2020.06.12-eihbyb4brvhwsp2znuoxozo7uwus7y4n/lib/hpctoolkit/ext-libs/libmonitor.so.0.0.0"/>
    <LoadModule i="669" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/libmpi.so.40.10.4"/>
    <LoadModule i="694" n="/opt/ohpc/pub/compiler/gcc/8.3.0/lib64/libgomp.so.1.0.0"/>
    <LoadModule i="780" n="/usr/lib64/libpthread-2.17.so"/>
    <LoadModule i="786" n="/usr/lib64/libc-2.17.so"/>
    <LoadModule i="815" n="/usr/lib64/ld-2.17.so"/>
    <LoadModule i="825" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/libopen-rte.so.40.10.4"/>
    <LoadModule i="835" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/libopen-pal.so.40.10.4"/>
    <LoadModule i="890" n="/usr/lib64/libevent-2.0.so.5.1.9"/>
    <LoadModule i="894" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_ess_pmi.so"/>
    <LoadModule i="900" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_pmix_ext2x.so"/>
    <LoadModule i="911" n="/opt/ohpc/admin/pmix/lib/libpmix.so.2.1.22"/>
    <LoadModule i="958" n="/opt/ohpc/admin/pmix/lib/pmix/mca_gds_hash.so"/>
    <LoadModule i="966" n="/usr/lib64/libibverbs.so.1.5.22.4"/>
    <LoadModule i="978" n="/usr/lib64/libbnxt_re-rdmav22.so"/>
    <LoadModule i="1000" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_rcache_grdma.so"/>
    <LoadModule i="1004" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_btl_vader.so"/>
    <LoadModule i="1013" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_btl_openib.so"/>
    <LoadModule i="1023" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_pml_ob1.so"/>
    <LoadModule i="1047" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_coll_tuned.so"/>
  </LoadModuleTable>
  <FileTable>
    <File i="3" n="./src/home/u10/ianbertolacci/testcode/HPCToolkit-Testing-Miniapp/mpi_omp/miniapp.c"/>
    <File i="553" n="&lt;unknown file&gt; [miniapp]"/>
    <File i="650" n="&lt;unknown file&gt;"/>
    <File i="654" n="&lt;unknown file&gt; [libhpcrun.so.0.0.0]"/>
    <File i="658" n="&lt;unknown file&gt; [libmonitor.so.0.0.0]"/>
    <File i="670" n="&lt;unknown file&gt; [libmpi.so.40.10.4]"/>
    <File i="683" n="pop_f2c.c"/>
    <File i="695" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/parallel.c"/>
    <File i="763" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/libgomp.h"/>
    <File i="706" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/team.c"/>
    <File i="713" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/linux/bar.h"/>
    <File i="718" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/posix/pool.h"/>
    <File i="710" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/alloc.c"/>
    <File i="729" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/task.c"/>
    <File i="742" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/linux/bar.c"/>
    <File i="747" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/linux/x86/futex.h"/>
    <File i="755" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/work.c"/>
    <File i="781" n="&lt;unknown file&gt; [libpthread-2.17.so]"/>
    <File i="787" n="iogetwline.c"/>
    <File i="790" n="&lt;unknown file&gt; [libc-2.17.so]"/>
    <File i="816" n="dl-sysdep.c"/>
    <File i="826" n="&lt;unknown file&gt; [libopen-rte.so.40.10.4]"/>
    <File i="836" n="opal_hash_table.c"/>
    <File i="839" n="&lt;unknown file&gt; [libopen-pal.so.40.10.4]"/>
    <File i="891" n="&lt;unknown file&gt; [libevent-2.0.so.5.1.9]"/>
    <File i="895" n="ess_pmi_component.c"/>
    <File i="901" n="&lt;unknown file&gt; [mca_pmix_ext2x.so]"/>
    <File i="906" n="crtstuff.c"/>
    <File i="912" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/client/pmix_client.c"/>
    <File i="918" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/runtime/pmix_progress_threads.c"/>
    <File i="927" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/runtime/pmix_finalize.c"/>
    <File i="929" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/class/pmix_object.h"/>
    <File i="931" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/event/pmix_event_notification.c"/>
    <File i="935" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/class/pmix_list.c"/>
    <File i="944" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/event/pmix_event_registration.c"/>
    <File i="950" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/mca/bfrops/base/bfrop_base_pack.c"/>
    <File i="959" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/mca/gds/hash/gds_hash.c"/>
    <File i="962" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/mca/gds/hash/../../../../include/pmix_common.h"/>
    <File i="967" n="&lt;unknown file&gt; [libibverbs.so.1.5.22.4]"/>
    <File i="979" n="&lt;unknown file&gt; [libbnxt_re-rdmav22.so]"/>
    <File i="1001" n="rcache_grdma_module.c"/>
    <File i="1005" n="&lt;unknown file&gt; [mca_btl_vader.so]"/>
    <File i="1008" n="btl_vader_module.c"/>
    <File i="1014" n="btl_openib_atomic.c"/>
    <File i="1024" n="&lt;unknown file&gt; [mca_pml_ob1.so]"/>
    <File i="1048" n="&lt;unknown file&gt; [mca_coll_tuned.so]"/>
  </FileTable>
  <ProcedureTable>
    <Procedure i="64" n="in_place_stencilize_local_array._omp_fn.3" v="0x401770"/>
    <Procedure i="459" n="in_place_stencilize_distributed_array" v="0x402ac0"/>
    <Procedure i="509" n="" v="0"/>
    <Procedure i="510" n="in_place_stencilize_local_array" v="0"/>
    <Procedure i="71" n="sum_local_array._omp_fn.4" v="0x4018f0"/>
    <Procedure i="527" n="sum_distributed_array" v="0x402ed0"/>
    <Procedure i="548" n="sum_local_array" v="0"/>
    <Procedure i="4" n="main" v="0x401200"/>
    <Procedure i="37" n="program_finalize" v="0"/>
    <Procedure i="583" n="free@plt" v="0x4010a0"/>
    <Procedure i="595" n="MPI_Wait@plt" v="0x401100"/>
    <Procedure i="651" n="&lt;partial call paths&gt;" f="1" v="0"/>
    <Procedure i="655" n="&lt;no activity&gt;" f="3" v="0"/>
    <Procedure i="659" n="&lt;program root&gt;" f="4" v="0"/>
    <Procedure i="665" n="MPI_Finalize" v="0"/>
    <Procedure i="667" n="&lt;thread root&gt;" f="4" v="0"/>
    <Procedure i="675" n="MPI_Isend" v="0"/>
    <Procedure i="677" n="MPI_Irecv" v="0"/>
    <Procedure i="679" n="MPI_Wait" v="0"/>
    <Procedure i="681" n="ompi_request_default_wait" v="0"/>
    <Procedure i="686" n="PMPI_Gather" v="0"/>
    <Procedure i="688" n="ompi_coll_base_gather_intra_basic_linear" v="0"/>
    <Procedure i="690" n="ompi_datatype_sndrcv" v="0"/>
    <Procedure i="692" n="ompi_mpi_finalize" v="0"/>
    <Procedure i="684" n="ompi_request_empty_free" v="0"/>
    <Procedure i="701" n="gomp_resolve_num_threads" v="0"/>
    <Procedure i="763" n="&lt;inline&gt;" v="0"/>
    <Procedure i="696" n="GOMP_parallel_end" v="0"/>
    <Procedure i="698" n="GOMP_parallel" v="0"/>
    <Procedure i="736" n="omp_get_num_threads" v="0"/>
    <Procedure i="776" n="omp_get_thread_num" v="0"/>
    <Procedure i="707" n="gomp_new_team" v="0"/>
    <Procedure i="713" n="&lt;inline&gt;" v="0"/>
    <Procedure i="718" n="&lt;inline&gt;" v="0"/>
    <Procedure i="720" n="&lt;inline&gt;" v="0"/>
    <Procedure i="722" n="gomp_team_start" v="0"/>
    <Procedure i="739" n="gomp_team_end" v="0"/>
    <Procedure i="711" n="gomp_malloc" v="0"/>
    <Procedure i="730" n="gomp_init_task" v="0"/>
    <Procedure i="732" n="&lt;inline&gt;" v="0"/>
    <Procedure i="759" n="gomp_end_task" v="0"/>
    <Procedure i="778" n="&lt;inline&gt;" v="0"/>
    <Procedure i="743" n="gomp_team_barrier_wait_end" v="0"/>
    <Procedure i="747" n="&lt;inline&gt;" v="0"/>
    <Procedure i="750" n="gomp_barrier_wait_final_start" v="0"/>
    <Procedure i="768" n="gomp_init_work_share" v="0"/>
    <Procedure i="756" n="gomp_fini_work_share" v="0"/>
    <Procedure i="782" n="pthread_spin_lock" v="0"/>
    <Procedure i="784" n="pthread_spin_init" v="0"/>
    <Procedure i="788" n="__ioctl" v="0"/>
    <Procedure i="793" n="__memcpy_ssse3" v="0"/>
    <Procedure i="797" n="_int_malloc" v="0"/>
    <Procedure i="799" n="malloc_consolidate" v="0"/>
    <Procedure i="801" n="_int_free" v="0"/>
    <Procedure i="803" n="__cfree" v="0"/>
    <Procedure i="809" n="__getdents64" v="0"/>
    <Procedure i="811" n="__GI___asprintf" v="0"/>
    <Procedure i="813" n="_IO_vasprintf" v="0"/>
    <Procedure i="791" n="syscall" v="0"/>
    <Procedure i="795" n="malloc" v="0"/>
    <Procedure i="805" n="__sched_yield" v="0"/>
    <Procedure i="807" n="readdir64" v="0"/>
    <Procedure i="817" n="_dl_runtime_resolve_xsavec" v="0"/>
    <Procedure i="819" n="_dl_fixup" v="0"/>
    <Procedure i="821" n="_dl_lookup_symbol_x" v="0"/>
    <Procedure i="823" n="do_lookup_x" v="0"/>
    <Procedure i="829" n="orte_finalize" v="0"/>
    <Procedure i="831" n="orte_ess_base_app_finalize" v="0"/>
    <Procedure i="833" n="orte_session_dir_finalize" v="0"/>
    <Procedure i="837" n="intercept_madvise" v="0"/>
    <Procedure i="850" n="opal_timer_linux_get_cycles_sys_timer" v="0"/>
    <Procedure i="852" n="non_overlap_copy_content_same_ddt" v="0"/>
    <Procedure i="860" n="mca_btl_base_close" v="0"/>
    <Procedure i="866" n="mca_mpool_base_close" v="0"/>
    <Procedure i="870" n="opal_rb_tree_destruct" v="0"/>
    <Procedure i="872" n="opal_free_list_destruct" v="0"/>
    <Procedure i="882" n="var_destructor" v="0"/>
    <Procedure i="884" n="mca_base_var_enum_destructor" v="0"/>
    <Procedure i="888" n="progress_engine" v="0"/>
    <Procedure i="844" n="opal_convertor_prepare_for_recv" v="0"/>
    <Procedure i="846" n="opal_convertor_unpack" v="0"/>
    <Procedure i="848" n="opal_progress" v="0"/>
    <Procedure i="854" n="opal_datatype_copy_content_same_ddt" v="0"/>
    <Procedure i="856" n="opal_convertor_prepare_for_send" v="0"/>
    <Procedure i="858" n="mca_base_framework_close" v="0"/>
    <Procedure i="862" n="mca_base_components_close" v="0"/>
    <Procedure i="864" n="mca_base_component_close" v="0"/>
    <Procedure i="868" n="mca_mpool_base_tree_fini" v="0"/>
    <Procedure i="874" n="opal_os_dirpath_destroy" v="0"/>
    <Procedure i="876" n="opal_finalize" v="0"/>
    <Procedure i="878" n="opal_finalize_util" v="0"/>
    <Procedure i="880" n="mca_base_var_finalize" v="0"/>
    <Procedure i="886" n="opal_unsetenv" v="0"/>
    <Procedure i="892" n="event_base_loop" v="0"/>
    <Procedure i="898" n="rte_finalize" v="0"/>
    <Procedure i="904" n="ext2x_client_finalize" v="0"/>
    <Procedure i="907" n="process_event" v="0"/>
    <Procedure i="909" n="return_local_event_hdlr" v="0"/>
    <Procedure i="925" n="PMIx_Finalize" v="0"/>
    <Procedure i="956" n="_commitfn" v="0"/>
    <Procedure i="942" n="progress_engine" v="0"/>
    <Procedure i="928" n="pmix_rte_finalize" v="0"/>
    <Procedure i="929" n="&lt;inline&gt;" v="0"/>
    <Procedure i="939" n="progress_local_event_hdlr" v="0"/>
    <Procedure i="932" n="evdes" v="0"/>
    <Procedure i="933" n="&lt;inline&gt;" v="0"/>
    <Procedure i="936" n="pmix_list_construct" v="0"/>
    <Procedure i="947" n="_add_hdlr" v="0"/>
    <Procedure i="948" n="&lt;inline&gt;" v="0"/>
    <Procedure i="945" n="reg_event_hdlr" v="0"/>
    <Procedure i="951" n="pmix_bfrops_base_pack" v="0"/>
    <Procedure i="953" n="pmix_bfrops_base_pack_int32" v="0"/>
    <Procedure i="960" n="hash_fetch" v="0"/>
    <Procedure i="963" n="pmix_value_destruct" v="0"/>
    <Procedure i="968" n="ibv_dereg_mr" v="0"/>
    <Procedure i="970" n="ibv_cmd_dereg_mr" v="0"/>
    <Procedure i="972" n="ibv_cmd_reg_dm_mr" v="0"/>
    <Procedure i="974" n="execute_ioctl" v="0"/>
    <Procedure i="976" n="ibv_copy_path_rec_to_kern" v="0"/>
    <Procedure i="980" n="&lt;unknown procedure&gt; 0x287c [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="982" n="&lt;unknown procedure&gt; 0x3870 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="984" n="&lt;unknown procedure&gt; 0x38b4 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="986" n="&lt;unknown procedure&gt; 0x3994 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="988" n="&lt;unknown procedure&gt; 0x2c90 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="990" n="&lt;unknown procedure&gt; 0x2cd0 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="992" n="&lt;unknown procedure&gt; 0x3068 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="994" n="&lt;unknown procedure&gt; 0x33a8 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="996" n="&lt;unknown procedure&gt; 0x39fd [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="998" n="&lt;unknown procedure&gt; 0x2cba [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1002" n="mca_rcache_grdma_deregister" v="0"/>
    <Procedure i="1006" n="mca_btl_vader_sendi" v="0"/>
    <Procedure i="1011" n="memcpy@plt" v="0"/>
    <Procedure i="1009" n="mca_btl_vader_component_progress" v="0"/>
    <Procedure i="1015" n="openib_dereg_mr" v="0"/>
    <Procedure i="1017" n="btl_openib_component_progress" v="0"/>
    <Procedure i="1019" n="poll_device" v="0"/>
    <Procedure i="1021" n="btl_openib_component_close" v="0"/>
    <Procedure i="1025" n="mca_pml_ob1_isend" v="0"/>
    <Procedure i="1027" n="mca_pml_ob1_send_inline.constprop.6" v="0"/>
    <Procedure i="1029" n="mca_pml_ob1_irecv" v="0"/>
    <Procedure i="1031" n="mca_pml_ob1_recv_req_start" v="0"/>
    <Procedure i="1033" n="mca_pml_ob1_recv_request_progress_match" v="0"/>
    <Procedure i="1035" n="mca_pml_ob1_recv_request_free" v="0"/>
    <Procedure i="1037" n="mca_pml_ob1_recv_frag_callback_match" v="0"/>
    <Procedure i="1039" n="match_one" v="0"/>
    <Procedure i="1041" n="mca_pml_ob1_recv" v="0"/>
    <Procedure i="1043" n="append_frag_to_list" v="0"/>
    <Procedure i="1045" n="mca_pml_ob1_send" v="0"/>
    <Procedure i="1049" n="ompi_coll_tuned_gather_intra_dec_fixed" v="0"/>
  </ProcedureTable>
  <Info/>
</SecHeader>
<SecCallPathProfileData>
<M n="24" v="6.99996"/>
<PF i="2" s="651" l="0" lm="649" f="650" n="651">
<M n="24" v="0.009762"/>
<C i="3" s="652" l="0" v="0x1">
<M n="24" v="0.009762"/>
<PF i="4" s="1002" l="0" lm="1000" f="1001" n="1002">
<M n="24" v="0.009762"/>
<C i="5" s="1003" l="0" v="0x22e9">
<M n="24" v="0.009762"/>
<PF i="6" s="1015" l="0" lm="1013" f="1014" n="1015">
<M n="24" v="0.009762"/>
<C i="7" s="1016" l="0" v="0xd6ad">
<M n="24" v="0.009762"/>
<PF i="8" s="968" l="0" lm="966" f="967" n="968">
<M n="24" v="0.009762"/>
<C i="9" s="969" l="0" v="0x127b3">
<M n="24" v="0.002931"/>
<PF i="10" s="980" l="0" lm="978" f="979" n="980">
<M n="24" v="0.002931"/>
<C i="11" s="981" l="0" v="0x287d">
<M n="24" v="0.002931"/>
<PF i="12" s="970" l="0" lm="966" f="967" n="970">
<M n="24" v="0.002931"/>
<C i="13" s="971" l="0" v="0xbed0">
<M n="24" v="0.002931"/>
<PF i="14" s="972" l="0" lm="966" f="967" n="972">
<M n="24" v="0.002931"/>
<C i="15" s="973" l="0" v="0xb082">
<M n="24" v="0.002931"/>
<PF i="16" s="972" l="0" lm="966" f="967" n="972">
<M n="24" v="0.002931"/>
<C i="17" s="973" l="0" v="0xac1f">
<M n="24" v="0.002931"/>
<PF i="18" s="974" l="0" lm="966" f="967" n="974">
<M n="24" v="0.002931"/>
<C i="19" s="975" l="0" v="0xba7f">
<M n="24" v="0.002931"/>
<PF i="20" s="788" l="0" lm="786" f="787" n="788">
<M n="24" v="0.002931"/><M n="25" v="0.002931"/>
<S i="21" s="789" l="0" it="589">
<M n="24" v="0.002931"/><M n="25" v="0.002931"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<C i="22" s="969" l="0" v="0x127e0">
<M n="24" v="0.006831"/>
<PF i="23" s="817" l="0" lm="815" f="816" n="817">
<M n="24" v="0.004007"/>
<C i="24" s="818" l="0" v="0x16a9a">
<M n="24" v="0.004007"/>
<PF i="25" s="819" l="0" lm="815" f="816" n="819">
<M n="24" v="0.004007"/><M n="25" v="0.004007"/>
<S i="26" s="820" l="0" it="713">
<M n="24" v="0.004007"/><M n="25" v="0.004007"/>
</S>
</PF>
</C>
</PF>
<PF i="27" s="976" l="0" lm="966" f="967" n="976">
<M n="24" v="0.002824"/>
<C i="28" s="977" l="0" v="0x1089c">
<M n="24" v="0.002824"/>
<PF i="29" s="837" l="0" lm="835" f="836" n="837">
<M n="24" v="0.002824"/>
<C i="30" s="838" l="0" v="0x73d8d">
<M n="24" v="0.002824"/>
<PF i="31" s="791" l="0" lm="786" f="790" n="791">
<M n="24" v="0.002824"/><M n="25" v="0.002824"/>
<S i="32" s="792" l="0" it="573">
<M n="24" v="0.002824"/><M n="25" v="0.002824"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
<PF i="33" s="655" l="0" lm="653" f="654" n="655">
<S i="34" s="656" l="0" it="663"/>
</PF>
<PF i="35" s="659" l="0" lm="657" f="658" n="659">
<M n="24" v="6.34649"/>
<C i="36" s="660" l="0" v="0xd76a">
<M n="24" v="6.34649"/>
<PF i="37" s="4" l="858" lm="2" f="3" n="4">
<M n="24" v="6.34649"/><M n="25" v="0.006989"/>
<S i="38" s="5" l="858" it="705"/>
<L i="39" s="26" l="879" f="3" v="0x401280">
<M n="24" v="6.28665"/><M n="25" v="0.006989"/>
<S i="40" s="30" l="885">
<M n="24" v="0.003996"/><M n="25" v="0.003996"/>
</S>
<C i="41" s="33" l="881" v="0x40128a">
<M n="24" v="4.28735"/>
<PF i="42" s="459" l="695" lm="2" f="3" n="459">
<M n="24" v="4.28735"/><M n="25" v="0.088855"/>
<S i="43" s="460" l="695" it="503"/>
<S i="44" s="467" l="720">
<M n="24" v="0.001994"/><M n="25" v="0.001994"/>
</S>
<S i="45" s="472" l="729">
<M n="24" v="0.002995"/><M n="25" v="0.002995"/>
</S>
<S i="46" s="483" l="766">
<M n="24" v="0.056945"/><M n="25" v="0.056945"/>
</S>
<S i="47" s="488" l="777">
<M n="24" v="0.003994"/><M n="25" v="0.003994"/>
</S>
<S i="48" s="489" l="781">
<M n="24" v="0.005945"/><M n="25" v="0.005945"/>
</S>
<S i="49" s="492" l="785">
<M n="24" v="0.002995"/><M n="25" v="0.002995"/>
</S>
<S i="50" s="493" l="791">
<M n="24" v="0.004994"/><M n="25" v="0.004994"/>
</S>
<S i="51" s="497" l="799">
<M n="24" v="0.008993"/><M n="25" v="0.008993"/>
</S>
<C i="52" s="498" l="721" v="0x402dab">
<M n="24" v="0.138269"/>
<PF i="53" s="675" l="0" lm="669" f="670" n="675">
<M n="24" v="0.138269"/><M n="25" v="0.050917"/>
<C i="54" s="676" l="0" v="0x7af25">
<M n="24" v="0.087352"/>
<PF i="55" s="1025" l="0" lm="1023" f="1024" n="1025">
<M n="24" v="0.087352"/><M n="25" v="0.030953"/>
<C i="56" s="1026" l="0" v="0xb8e7">
<M n="24" v="0.056399"/>
<PF i="57" s="1027" l="0" lm="1023" f="1024" n="1027">
<M n="24" v="0.056399"/><M n="25" v="0.044415"/>
<C i="58" s="1028" l="0" v="0xad68">
<M n="24" v="0.011984"/>
<PF i="59" s="1006" l="0" lm="1004" f="1005" n="1006">
<M n="24" v="0.011984"/><M n="25" v="0.005996"/>
<C i="60" s="1007" l="0" v="0x570f">
<M n="24" v="0.005988"/>
<PF i="61" s="793" l="0" lm="786" f="787" n="793">
<M n="24" v="0.005988"/><M n="25" v="0.005988"/>
<S i="62" s="794" l="0" it="591">
<M n="24" v="0.005988"/><M n="25" v="0.005988"/>
</S>
</PF>
</C>
<S i="63" s="1007" l="0" it="649">
<M n="24" v="0.005996"/><M n="25" v="0.005996"/>
</S>
</PF>
</C>
<S i="64" s="1028" l="0" it="265">
<M n="24" v="0.044415"/><M n="25" v="0.044415"/>
</S>
</PF>
</C>
<S i="65" s="1026" l="0" it="177">
<M n="24" v="0.030953"/><M n="25" v="0.030953"/>
</S>
</PF>
</C>
<S i="66" s="676" l="0" it="327">
<M n="24" v="0.050917"/><M n="25" v="0.050917"/>
</S>
</PF>
</C>
<C i="67" s="499" l="728" v="0x402de8">
<M n="24" v="0.12682"/>
<PF i="68" s="677" l="0" lm="669" f="670" n="677">
<M n="24" v="0.12682"/><M n="25" v="0.032961"/>
<C i="69" s="678" l="0" v="0x7a8e5">
<M n="24" v="0.093859"/>