<?xml version="1.0"?>
<!DOCTYPE HPCToolkitExperiment [
<!-- ******************************************************************** -->
<!-- HPCToolkit Experiment DTD						  -->
<!-- Version 2.2							  -->
<!-- ******************************************************************** -->
<!ELEMENT HPCToolkitExperiment (Header, (SecCallPathProfile|SecFlatProfile)*)>
<!ATTLIST HPCToolkitExperiment
	  version CDATA #REQUIRED>

  <!-- ****************************************************************** -->

  <!-- Info/NV: flexible name-value pairs: (n)ame; (t)ype; (v)alue -->
  <!ELEMENT Info (NV*)>
  <!ATTLIST Info
	    n CDATA #IMPLIED>
  <!ELEMENT NV EMPTY>
  <!ATTLIST NV
	    n CDATA #REQUIRED
	    t CDATA #IMPLIED
	    v CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Header								  -->
  <!-- ****************************************************************** -->
  <!ELEMENT Header (Info*)>
  <!ATTLIST Header
	    n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section Header							  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecHeader (MetricTable?, MetricDBTable?, TraceDBTable?, LoadModuleTable?, FileTable?, ProcedureTable?, Info*)>

    <!-- MetricTable: -->
    <!ELEMENT MetricTable (Metric)*>

    <!-- Metric: (i)d; (n)ame -->
    <!--   o: metric sequence order (hpcrun metric order) -->
    <!--   md: metric description -->
    <!--   mp: metric parent ID   -->
    <!--   es: number of samples    (perf_events only) -->
    <!--   em: event multiplexed    (perf_events only) -->
    <!--   ep: average event period (perf_events only) -->
    <!--   (v)alue-type: transient type of values -->
    <!--   (t)ype: persistent type of metric      -->
    <!--   show: metric visibility type. Possible values: -->
    <!--        0: hidden -->
    <!--        1: shown  -->
    <!--        2: show inclusive metric only -->
    <!--        3: show exclusive metric only -->
    <!--        4: invisible, do not show at all -->
    <!--   show-percent: whether to show the percent (1) or not (0)  -->
    <!--   partner: the exclusive or inclusive partner ID of this metric -->
    <!--   fmt: format; show; -->
    <!ELEMENT Metric (MetricFormula*, Info?)>
    <!ATTLIST Metric
	      i            CDATA #REQUIRED
	      o	           CDATA #IMPLIED
	      n            CDATA #REQUIRED
	      md           CDATA #IMPLIED
	      mp           CDATA #IMPLIED
	      es           CDATA #IMPLIED
	      em           CDATA #IMPLIED
	      ep           CDATA #IMPLIED
	      v            (raw|final|derived-incr|derived) "raw"
	      t            (inclusive|exclusive|nil) "nil"
	      partner      CDATA #IMPLIED
	      fmt          CDATA #IMPLIED
	      show         (1|0|2|3|4) "1"
	      show-percent (1|0) "1">

    <!-- MetricFormula represents derived metrics: (t)ype; (frm): formula -->
    <!ELEMENT MetricFormula (Info?)>
    <!ATTLIST MetricFormula
	      t   (combine|finalize|view) "finalize"
	      i   CDATA #IMPLIED
	      frm CDATA #REQUIRED>

    <!-- Metric data, used in sections: (n)ame [from Metric]; (v)alue -->
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	      n CDATA #REQUIRED
	      v CDATA #REQUIRED>

    <!-- MetricDBTable: -->
    <!ELEMENT MetricDBTable (MetricDB)*>

    <!-- MetricDB: (i)d; (n)ame -->
    <!--   (t)ype: persistent type of metric -->
    <!--   db-glob:        file glob describing files in metric db -->
    <!--   db-id:          id within metric db -->
    <!--   db-num-metrics: number of metrics in db -->
    <!--   db-header-sz:   size (in bytes) of a db file header -->
    <!ELEMENT MetricDB EMPTY>
    <!ATTLIST MetricDB
	      i              CDATA #REQUIRED
	      n              CDATA #REQUIRED
	      t              (inclusive|exclusive|nil) "nil"
	      partner        CDATA #IMPLIED
	      db-glob        CDATA #IMPLIED
	      db-id          CDATA #IMPLIED
	      db-num-metrics CDATA #IMPLIED
	      db-header-sz   CDATA #IMPLIED>

    <!-- TraceDBTable: -->
    <!ELEMENT TraceDBTable (TraceDB)>

    <!-- TraceDB: (i)d -->
    <!--   u: unit time of the trace (ms, ns, ..) -->
    <!--   db-min-time: min beginning time stamp (global) -->
    <!--   db-max-time: max ending time stamp (global) -->
    <!ELEMENT TraceDB EMPTY>
    <!ATTLIST TraceDB
	      i            CDATA #REQUIRED
	      u            CDATA #IMPLIED
	      db-glob      CDATA #IMPLIED
	      db-min-time  CDATA #IMPLIED
	      db-max-time  CDATA #IMPLIED
	      db-header-sz CDATA #IMPLIED>

    <!-- LoadModuleTable assigns a short name to a load module -->
    <!ELEMENT LoadModuleTable (LoadModule)*>

    <!ELEMENT LoadModule (Info?)>
    <!ATTLIST LoadModule
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- FileTable assigns a short name to a file -->
    <!ELEMENT FileTable (File)*>

    <!ELEMENT File (Info?)>
    <!ATTLIST File
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- ProcedureTable assigns a short name to a procedure -->
    <!ELEMENT ProcedureTable (Procedure)*>

    <!-- Dictionary for procedure: (i)d, (n)ame, (f)eature and (v)alue of the address -->
    <!-- Possible value of f: -->
    <!-- 0: normal procedure -->
    <!-- 1: place holder, do not add anything -->
    <!-- 2: root-type, has to be shown in a separate view -->
    <!-- 3: invisible in hpcviewer, but visible in hpctraceviewer  -->
    <!ELEMENT Procedure (Info?)>
    <!ATTLIST Procedure
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED
	      f CDATA #IMPLIED
	      v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Call path profile					  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecCallPathProfile (SecHeader, SecCallPathProfileData)>
  <!ATTLIST SecCallPathProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecCallPathProfileData (PF|M)*>
      <!-- Procedure frame -->
      <!--   (i)d: unique identifier for cross referencing -->
      <!--   (s)tatic scope id -->
      <!--   (n)ame: a string or an id in ProcedureTable -->
      <!--   (lm) load module: a string or an id in LoadModuleTable -->
      <!--   (f)ile name: a string or an id in LoadModuleTable -->
      <!--   (l)ine range: "beg-end" (inclusive range) -->
      <!--   (a)lien: whether frame is alien to enclosing P -->
      <!--   (str)uct: hpcstruct node id -->
      <!--   (v)ma-range-set: "{[beg-end), [beg-end)...}" -->
      <!ELEMENT PF (PF|Pr|L|C|S|M)*>
      <!ATTLIST PF
		i  CDATA #IMPLIED
		s  CDATA #IMPLIED
		n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Procedure (static): GOAL: replace with 'P' -->
      <!ELEMENT Pr (Pr|L|C|S|M)*>
      <!ATTLIST Pr
                i  CDATA #IMPLIED
		s  CDATA #IMPLIED
                n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
                l  CDATA #IMPLIED
		a  (1|0) "0"
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Callsite (a special StatementRange) -->
      <!ELEMENT C (PF|M)*>
      <!ATTLIST C
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Flat profile						  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecFlatProfile (SecHeader, SecFlatProfileData)>
  <!ATTLIST SecFlatProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecFlatProfileData (LM|M)*>
      <!-- Load module: (i)d; (n)ame; (v)ma-range-set -->
      <!ELEMENT LM (F|P|M)*>
      <!ATTLIST LM
                i CDATA #IMPLIED
                n CDATA #REQUIRED
		v CDATA #IMPLIED>
      <!-- File -->
      <!ELEMENT F (P|L|S|M)*>
      <!ATTLIST F
                i CDATA #IMPLIED
                n CDATA #REQUIRED>
      <!-- Procedure (Note 1) -->
      <!ELEMENT P (P|A|L|S|C|M)*>
      <!ATTLIST P
                i CDATA #IMPLIED
                n CDATA #REQUIRED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Alien (Note 1) -->
      <!ELEMENT A (A|L|S|C|M)*>
      <!ATTLIST A
                i CDATA #IMPLIED
                f CDATA #IMPLIED
                n CDATA #IMPLIED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Loop (Note 1,2) -->
      <!ELEMENT L (A|Pr|L|S|C|M)*>
      <!ATTLIST L
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
	        f CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Statement (Note 2) -->
      <!--   (it): trace record identifier -->
      <!ELEMENT S (S|M)*>
      <!ATTLIST S
		i  CDATA #IMPLIED
		it CDATA #IMPLIED
		s  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Note 1: Contained Cs may not contain PFs -->
      <!-- Note 2: The 's' attribute is not used for flat profiles -->
]>
<HPCToolkitExperiment version="2.2">
<Header n="miniapp">
  <Info/>
</Header>
<SecCallPathProfile i="0" n="miniapp">
<SecHeader>
  <MetricTable>
    <Metric i="24" n="CPUTIME (sec):Sum (I)" o="0" v="derived-incr" md="CPUTIME (sec)" em="0" es="0" ep="0" t="inclusive" partner="25" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($24, $24)"/>
      <MetricFormula t="finalize" frm="$24"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="25" n="CPUTIME (sec):Sum (E)" o="-1" v="derived-incr" md="CPUTIME (sec)" em="0" es="0" ep="0" t="exclusive" partner="24" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($25, $25)"/>
      <MetricFormula t="finalize" frm="$25"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
  </MetricTable>
  <MetricDBTable>
  </MetricDBTable>
  <TraceDBTable>
    <TraceDB i="0" u="1000000000" db-glob="*.hpctrace" db-min-time="1596577331872443000" db-max-time="1596577366286031000" db-header-sz="32"/>
  </TraceDBTable>
  <LoadModuleTable>
    <LoadModule i="2" n="/home/u10/ianbertolacci/testcode/HPCToolkit-Testing-Miniapp/mpi_omp/miniapp"/>
    <LoadModule i="653" n="/opt/ohpc/pub/apps/hpctoolkit/2020.06/linux-centos7-zen/gcc-8.3.0/hpctoolkit-2020.06.12-eihbyb4brvhwsp2znuoxozo7uwus7y4n/lib/hpctoolkit/libhpcrun.so.0.0.0"/>
    <LoadModule i="657" n="/opt/ohpc/pub/apps/hpctoolkit/2020.06/linux-centos7-zen/gcc-8.3.0/hpctoolkit-2020.06.12-eihbyb4brvhwsp2znuoxozo7uwus7y4n/lib/hpctoolkit/ext-libs/libmonitor.so.0.0.0"/>
    <LoadModule i="669" n="/usr/lib64/libm-2.17.so"/>
    <LoadModule i="673" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/libmpi.so.40.10.4"/>
    <LoadModule i="704" n="/opt/ohpc/pub/compiler/gcc/8.3.0/lib64/libgomp.so.1.0.0"/>
    <LoadModule i="796" n="/usr/lib64/libpthread-2.17.so"/>
    <LoadModule i="800" n="/usr/lib64/libc-2.17.so"/>
    <LoadModule i="833" n="/usr/lib64/ld-2.17.so"/>
    <LoadModule i="847" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/libopen-rte.so.40.10.4"/>
    <LoadModule i="858" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/libopen-pal.so.40.10.4"/>
    <LoadModule i="901" n="/usr/lib64/libhwloc.so.5.7.5"/>
    <LoadModule i="907" n="/usr/lib64/libevent-2.0.so.5.1.9"/>
    <LoadModule i="911" n="/usr/lib64/libltdl.so.7.3.0"/>
    <LoadModule i="917" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_ess_pmi.so"/>
    <LoadModule i="923" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_pmix_ext2x.so"/>
    <LoadModule i="929" n="/opt/ohpc/admin/pmix/lib/libpmix.so.2.1.22"/>
    <LoadModule i="973" n="/usr/lib64/libbnxt_re-rdmav22.so"/>
    <LoadModule i="983" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_btl_vader.so"/>
    <LoadModule i="990" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_btl_openib.so"/>
    <LoadModule i="1003" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_pml_ob1.so"/>
    <LoadModule i="1030" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_coll_tuned.so"/>
  </LoadModuleTable>
  <FileTable>
    <File i="3" n="./src/home/u10/ianbertolacci/testcode/HPCToolkit-Testing-Miniapp/mpi_omp/miniapp.c"/>
    <File i="553" n="&lt;unknown file&gt; [miniapp]"/>
    <File i="654" n="&lt;unknown file&gt; [libhpcrun.so.0.0.0]"/>
    <File i="658" n="&lt;unknown file&gt; [libmonitor.so.0.0.0]"/>
    <File i="670" n="fraiseexcpt.c"/>
    <File i="674" n="&lt;unknown file&gt; [libmpi.so.40.10.4]"/>
    <File i="687" n="pgroup_translate_ranks.c"/>
    <File i="705" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/parallel.c"/>
    <File i="717" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/libgomp.h"/>
    <File i="723" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/team.c"/>
    <File i="733" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/posix/pool.h"/>
    <File i="727" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/alloc.c"/>
    <File i="745" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/task.c"/>
    <File i="786" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/priority_queue.h"/>
    <File i="761" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/linux/bar.c"/>
    <File i="765" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/linux/x86/futex.h"/>
    <File i="768" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/linux/bar.h"/>
    <File i="780" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/work.c"/>
    <File i="797" n="&lt;unknown file&gt; [libpthread-2.17.so]"/>
    <File i="801" n="mul_n.c"/>
    <File i="804" n="&lt;unknown file&gt; [libc-2.17.so]"/>
    <File i="834" n="strstr-c.c"/>
    <File i="848" n="&lt;unknown file&gt; [libopen-rte.so.40.10.4]"/>
    <File i="855" n="pmix_server_register_fns.c"/>
    <File i="859" n="&lt;unknown file&gt; [libopen-pal.so.40.10.4]"/>
    <File i="872" n="dss_print.c"/>
    <File i="902" n="&lt;unknown file&gt; [libhwloc.so.5.7.5]"/>
    <File i="908" n="&lt;unknown file&gt; [libevent-2.0.so.5.1.9]"/>
    <File i="912" n="&lt;unknown file&gt; [libltdl.so.7.3.0]"/>
    <File i="918" n="ess_pmi_component.c"/>
    <File i="924" n="&lt;unknown file&gt; [mca_pmix_ext2x.so]"/>
    <File i="930" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/client/pmix_client.c"/>
    <File i="936" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/runtime/pmix_progress_threads.c"/>
    <File i="945" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/runtime/pmix_finalize.c"/>
    <File i="952" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/class/pmix_hotel.h"/>
    <File i="948" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/mca/base/pmix_mca_base_var.c"/>
    <File i="950" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/class/pmix_object.h"/>
    <File i="960" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/mca/ptl/base/ptl_base_sendrecv.c"/>
    <File i="965" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/mca/bfrops/base/bfrop_base_unpack.c"/>
    <File i="974" n="&lt;unknown file&gt; [libbnxt_re-rdmav22.so]"/>
    <File i="984" n="&lt;unknown file&gt; [mca_btl_vader.so]"/>
    <File i="987" n="btl_vader_component.c"/>
    <File i="991" n="btl_openib_async.c"/>
    <File i="998" n="&lt;unknown file&gt; [mca_btl_openib.so]"/>
    <File i="1004" n="&lt;unknown file&gt; [mca_pml_ob1.so]"/>
    <File i="1007" n="pml_ob1_progress.c"/>
    <File i="1031" n="&lt;unknown file&gt; [mca_coll_tuned.so]"/>
  </FileTable>
  <ProcedureTable>
    <Procedure i="426" n="free_distributed_array" v="0x402970"/>
    <Procedure i="440" n="init_distributed_array" v="0x4029d0"/>
    <Procedure i="53" n="init_distributed_array._omp_fn.2" v="0x4015b0"/>
    <Procedure i="64" n="in_place_stencilize_local_array._omp_fn.3" v="0x401770"/>
    <Procedure i="459" n="in_place_stencilize_distributed_array" v="0x402ac0"/>
    <Procedure i="509" n="" v="0"/>
    <Procedure i="510" n="in_place_stencilize_local_array" v="0"/>
    <Procedure i="71" n="sum_local_array._omp_fn.4" v="0x4018f0"/>
    <Procedure i="527" n="sum_distributed_array" v="0x402ed0"/>
    <Procedure i="548" n="sum_local_array" v="0"/>
    <Procedure i="4" n="main" v="0x401200"/>
    <Procedure i="37" n="program_finalize" v="0"/>
    <Procedure i="569" n="MPI_Irecv@plt" v="0x401030"/>
    <Procedure i="655" n="&lt;no activity&gt;" f="3" v="0"/>
    <Procedure i="659" n="&lt;program root&gt;" f="4" v="0"/>
    <Procedure i="665" n="MPI_Finalize" v="0"/>
    <Procedure i="667" n="&lt;thread root&gt;" f="4" v="0"/>
    <Procedure i="671" n="__sin_avx" v="0"/>
    <Procedure i="679" n="MPI_Isend" v="0"/>
    <Procedure i="681" n="PMPI_Irecv" v="0"/>
    <Procedure i="683" n="PMPI_Wait" v="0"/>
    <Procedure i="685" n="ompi_request_default_wait" v="0"/>
    <Procedure i="690" n="PMPI_Gather" v="0"/>
    <Procedure i="692" n="ompi_coll_base_gather_intra_basic_linear" v="0"/>
    <Procedure i="694" n="ompi_datatype_sndrcv" v="0"/>
    <Procedure i="696" n="ompi_mpi_finalize" v="0"/>
    <Procedure i="698" n="ompi_comm_finalize" v="0"/>
    <Procedure i="700" n="ompi_attr_delete_all" v="0"/>
    <Procedure i="688" n="ompi_request_empty_free" v="0"/>
    <Procedure i="702" n="compare_attr_sequence" v="0"/>
    <Procedure i="715" n="gomp_resolve_num_threads" v="0"/>
    <Procedure i="717" n="&lt;inline&gt;" v="0"/>
    <Procedure i="708" n="GOMP_parallel_end" v="0"/>
    <Procedure i="710" n="&lt;inline&gt;" v="0"/>
    <Procedure i="706" n="GOMP_parallel" v="0"/>
    <Procedure i="751" n="omp_get_num_threads" v="0"/>
    <Procedure i="754" n="omp_get_thread_num" v="0"/>
    <Procedure i="724" n="gomp_new_team" v="0"/>
    <Procedure i="733" n="&lt;inline&gt;" v="0"/>
    <Procedure i="737" n="gomp_team_start" v="0"/>
    <Procedure i="758" n="gomp_team_end" v="0"/>
    <Procedure i="728" n="gomp_malloc" v="0"/>
    <Procedure i="746" n="gomp_init_task" v="0"/>
    <Procedure i="748" n="&lt;inline&gt;" v="0"/>
    <Procedure i="786" n="&lt;inline&gt;" v="0"/>
    <Procedure i="774" n="gomp_end_task" v="0"/>
    <Procedure i="792" n="&lt;inline&gt;" v="0"/>
    <Procedure i="762" n="gomp_team_barrier_wait_end" v="0"/>
    <Procedure i="765" n="&lt;inline&gt;" v="0"/>
    <Procedure i="769" n="gomp_barrier_wait_final_start" v="0"/>
    <Procedure i="781" n="gomp_init_work_share" v="0"/>
    <Procedure i="798" n="pthread_spin_lock" v="0"/>
    <Procedure i="802" n="__memcpy_ssse3" v="0"/>
    <Procedure i="807" n="_int_malloc" v="0"/>
    <Procedure i="809" n="malloc_consolidate" v="0"/>
    <Procedure i="813" n="_int_free" v="0"/>
    <Procedure i="817" n="__GI_memset" v="0"/>
    <Procedure i="819" n="systrim.isra.2" v="0"/>
    <Procedure i="827" n="__qsort_r" v="0"/>
    <Procedure i="829" n="msort_with_tmp.part.0" v="0"/>
    <Procedure i="805" n="__libc_malloc" v="0"/>
    <Procedure i="811" n="__libc_free" v="0"/>
    <Procedure i="815" n="__sched_yield" v="0"/>
    <Procedure i="821" n="__default_morecore" v="0"/>
    <Procedure i="823" n="__sbrk" v="0"/>
    <Procedure i="825" n="syscall" v="0"/>
    <Procedure i="831" n="writev" v="0"/>
    <Procedure i="835" n="_dl_runtime_resolve_xsavec" v="0"/>
    <Procedure i="837" n="_dl_fixup" v="0"/>
    <Procedure i="839" n="_dl_lookup_symbol_x" v="0"/>
    <Procedure i="841" n="do_lookup_x" v="0"/>
    <Procedure i="843" n="check_match.9525" v="0"/>
    <Procedure i="845" n="strcmp" v="0"/>
    <Procedure i="851" n="orte_finalize" v="0"/>
    <Procedure i="853" n="orte_ess_base_app_finalize" v="0"/>
    <Procedure i="856" n="orte_dfs_base_close" v="0"/>
    <Procedure i="864" n="opal_convertor_prepare_for_recv" v="0"/>
    <Procedure i="866" n="opal_convertor_unpack" v="0"/>
    <Procedure i="868" n="opal_progress" v="0"/>
    <Procedure i="870" n="memcpy@plt" v="0"/>
    <Procedure i="877" n="opal_datatype_copy_content_same_ddt" v="0"/>
    <Procedure i="881" n="mca_base_framework_close" v="0"/>
    <Procedure i="885" n="mca_base_components_close" v="0"/>
    <Procedure i="887" n="mca_base_component_close" v="0"/>
    <Procedure i="889" n="opal_finalize" v="0"/>
    <Procedure i="893" n="opal_finalize_util" v="0"/>
    <Procedure i="895" n="mca_base_var_finalize" v="0"/>
    <Procedure i="899" n="opal_hash_table_remove_all" v="0"/>
    <Procedure i="873" n="opal_timer_linux_get_cycles_sys_timer" v="0"/>
    <Procedure i="875" n="non_overlap_copy_content_same_ddt" v="0"/>
    <Procedure i="879" n="intercept_brk" v="0"/>
    <Procedure i="883" n="mca_btl_base_close" v="0"/>
    <Procedure i="891" n="opal_hwloc_base_close" v="0"/>
    <Procedure i="897" n="opal_hash_table_destruct" v="0"/>
    <Procedure i="903" n="hwloc_topology_destroy" v="0"/>
    <Procedure i="905" n="hwloc_topology_set_distance_matrix" v="0"/>
    <Procedure i="909" n="event_base_loop" v="0"/>
    <Procedure i="913" n="lt_dlexit" v="0"/>
    <Procedure i="915" n="lt_dlloader_remove" v="0"/>
    <Procedure i="921" n="rte_finalize" v="0"/>
    <Procedure i="927" n="ext2x_client_finalize" v="0"/>
    <Procedure i="963" n="job_data" v="0"/>
    <Procedure i="943" n="PMIx_Finalize" v="0"/>
    <Procedure i="958" n="progress_engine" v="0"/>
    <Procedure i="955" n="pmix_progress_thread_pause" v="0"/>
    <Procedure i="956" n="&lt;inline&gt;" v="0"/>
    <Procedure i="946" n="pmix_rte_finalize" v="0"/>
    <Procedure i="952" n="&lt;inline&gt;" v="0"/>
    <Procedure i="949" n="pmix_mca_base_var_finalize" v="0"/>
    <Procedure i="950" n="&lt;inline&gt;" v="0"/>
    <Procedure i="970" n="pmix_ptl_base_send_handler" v="0"/>
    <Procedure i="971" n="&lt;inline&gt;" v="0"/>
    <Procedure i="961" n="pmix_ptl_base_process_msg" v="0"/>
    <Procedure i="966" n="pmix_bfrops_base_unpack" v="0"/>
    <Procedure i="968" n="pmix_bfrops_base_unpack_int32" v="0"/>
    <Procedure i="975" n="&lt;unknown procedure&gt; 0x38b4 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="977" n="&lt;unknown procedure&gt; 0x3994 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="979" n="&lt;unknown procedure&gt; 0x2c90 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="981" n="&lt;unknown procedure&gt; 0x2cd0 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="985" n="mca_btl_vader_sendi" v="0"/>
    <Procedure i="988" n="mca_btl_vader_component_progress" v="0"/>
    <Procedure i="992" n="btl_openib_component_progress" v="0"/>
    <Procedure i="994" n="poll_device" v="0"/>
    <Procedure i="996" n="btl_openib_component_close" v="0"/>
    <Procedure i="1001" n="rdmacm_component_finalize" v="0"/>
    <Procedure i="999" n="opal_btl_openib_connect_base_finalize" v="0"/>
    <Procedure i="1005" n="mca_pml_ob1_isend" v="0"/>
    <Procedure i="1010" n="mca_pml_ob1_irecv" v="0"/>
    <Procedure i="1012" n="mca_pml_ob1_recv_req_start" v="0"/>
    <Procedure i="1014" n="mca_pml_ob1_recv_request_progress_match" v="0"/>
    <Procedure i="1018" n="mca_pml_ob1_recv_frag_callback_match" v="0"/>
    <Procedure i="1024" n="opal_convertor_prepare_for_recv@plt" v="0"/>
    <Procedure i="1026" n="mca_pml_ob1_recv" v="0"/>
    <Procedure i="1028" n="mca_pml_ob1_send" v="0"/>
    <Procedure i="1008" n="mca_pml_ob1_send_inline.constprop.6" v="0"/>
    <Procedure i="1016" n="mca_pml_ob1_recv_request_free" v="0"/>
    <Procedure i="1020" n="match_one" v="0"/>
    <Procedure i="1022" n="append_frag_to_list" v="0"/>
    <Procedure i="1032" n="ompi_coll_tuned_gather_intra_dec_fixed" v="0"/>
  </ProcedureTable>
  <Info/>
</SecHeader>
<SecCallPathProfileData>
<M n="24" v="169.319"/>
<PF i="2" s="655" l="0" lm="653" f="654" n="655">
<S i="3" s="656" l="0" it="781"/>
</PF>
<PF i="4" s="659" l="0" lm="657" f="658" n="659">
<M n="24" v="135.051"/>
<C i="5" s="660" l="0" v="0xd76a">
<M n="24" v="135.051"/>
<PF i="6" s="4" l="858" lm="2" f="3" n="4">
<M n="24" v="135.051"/>
<C i="7" s="23" l="876" v="0x401260">
<M n="24" v="0.000467"/>
<PF i="8" s="440" l="640" lm="2" f="3" n="440">
<M n="24" v="0.000467"/>
<C i="9" s="445" l="643" v="0x4029f0">
<M n="24" v="0.000467"/>
<PF i="10" s="706" l="165" lm="704" f="705" n="706">
<M n="24" v="0.000467"/>
<C i="11" s="707" l="168" v="0xd93f">
<M n="24" v="0.000467"/>
<PF i="12" s="53" l="643" lm="2" f="3" n="53">
<M n="24" v="0.000467"/><M n="25" v="0.000382"/>
<S i="13" s="54" l="643" it="75"/>
<L i="14" s="61" l="644" f="3" v="0x40174d">
<M n="24" v="0.000467"/><M n="25" v="0.000382"/>
<S i="15" s="62" l="644">
<M n="24" v="0.000382"/><M n="25" v="0.000382"/>
</S>
<C i="16" s="63" l="644" v="0x401739">
<M n="24" v="8.5e-05"/>
<PF i="17" s="671" l="0" lm="669" f="670" n="671">
<M n="24" v="8.5e-05"/><M n="25" v="8.5e-05"/>
<S i="18" s="672" l="0" it="77">
<M n="24" v="8.5e-05"/><M n="25" v="8.5e-05"/>
</S>
</PF>
</C>
</L>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<C i="19" s="25" l="901" v="0x4012f9">
<M n="24" v="0.00101"/>
<PF i="20" s="426" l="629" lm="2" f="3" n="426">
<M n="24" v="0.00101"/>
<C i="21" s="431" l="630" v="0x402981">
<M n="24" v="0.00101"/>
<PF i="22" s="813" l="0" lm="800" f="801" n="813">
<M n="24" v="0.00101"/>
<C i="23" s="814" l="0" v="0x8115a">
<M n="24" v="0.00101"/>
<PF i="24" s="819" l="0" lm="800" f="801" n="819">
<M n="24" v="0.00101"/>
<C i="25" s="820" l="0" v="0x7f49a">
<M n="24" v="0.00101"/>
<PF i="26" s="821" l="0" lm="800" f="804" n="821">
<M n="24" v="0.00101"/>
<C i="27" s="822" l="0" v="0x88e49">
<M n="24" v="0.00101"/>
<PF i="28" s="823" l="0" lm="800" f="804" n="823">
<M n="24" v="0.00101"/>
<C i="29" s="824" l="0" v="0xf5286">
<M n="24" v="0.00101"/>
<PF i="30" s="879" l="0" lm="858" f="872" n="879">
<M n="24" v="0.00101"/>
<C i="31" s="880" l="0" v="0x73d05">
<M n="24" v="0.00101"/>
<PF i="32" s="825" l="0" lm="800" f="804" n="825">
<M n="24" v="0.00101"/><M n="25" v="0.00101"/>
<S i="33" s="826" l="0" it="807">
<M n="24" v="0.00101"/><M n="25" v="0.00101"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<L i="34" s="26" l="879" f="3" v="0x401280">
<M n="24" v="134.983"/>
<C i="35" s="33" l="881" v="0x40128a">
<M n="24" v="104.191"/>
<PF i="36" s="459" l="695" lm="2" f="3" n="459">
<M n="24" v="104.191"/><M n="25" v="0.034904"/>
<S i="37" s="460" l="695" it="93"/>
<S i="38" s="463" l="702">
<M n="24" v="0.002992"/><M n="25" v="0.002992"/>
</S>
<S i="39" s="464" l="703">
<M n="24" v="0.005973"/><M n="25" v="0.005973"/>
</S>
<S i="40" s="480" l="746">
<M n="24" v="0.001995"/><M n="25" v="0.001995"/>
</S>
<S i="41" s="483" l="766">
<M n="24" v="0.005984"/><M n="25" v="0.005984"/>
</S>
<S i="42" s="485" l="773">
<M n="24" v="0.001996"/><M n="25" v="0.001996"/>
</S>
<S i="43" s="486" l="774">
<M n="24" v="0.006992"/><M n="25" v="0.006992"/>
</S>
<S i="44" s="488" l="777">
<M n="24" v="0.005986"/><M n="25" v="0.005986"/>
</S>
<C i="45" s="498" l="721" v="0x402dab">
<M n="24" v="0.054765"/>
<PF i="46" s="679" l="0" lm="673" f="674" n="679">
<M n="24" v="0.054765"/><M n="25" v="0.011947"/>
<C i="47" s="680" l="0" v="0x7af25">
<M n="24" v="0.042818"/>
<PF i="48" s="1005" l="0" lm="1003" f="1004" n="1005">
<M n="24" v="0.042818"/><M n="25" v="0.006971"/>
<C i="49" s="1006" l="0" v="0xb8e7">
<M n="24" v="0.035847"/>
<PF i="50" s="1008" l="0" lm="1003" f="1007" n="1008">
<M n="24" v="0.035847"/><M n="25" v="0.008961"/>
<C i="51" s="1009" l="0" v="0xad68">
<M n="24" v="0.026886"/>
<PF i="52" s="985" l="0" lm="983" f="984" n="985">
<M n="24" v="0.026886"/><M n="25" v="0.014965"/>
<C i="53" s="986" l="0" v="0x570f">
<M n="24" v="0.004983"/>
<PF i="54" s="802" l="0" lm="800" f="801" n="802">
<M n="24" v="0.004983"/><M n="25" v="0.004983"/>
<S i="55" s="803" l="0" it="561">
<M n="24" v="0.004983"/><M n="25" v="0.004983"/>
</S>
</PF>
</C>
<C i="56" s="986" l="0" v="0x5bd9">
<M n="24" v="0.006938"/>
<PF i="57" s="817" l="0" lm="800" f="801" n="817">
<M n="24" v="0.006938"/><M n="25" v="0.006938"/>
<S i="58" s="818" l="0" it="91">
<M n="24" v="0.006938"/><M n="25" v="0.006938"/>
</S>
</PF>
</C>
<S i="59" s="986" l="0" it="793">
<M n="24" v="0.014965"/><M n="25" v="0.014965"/>
</S>
</PF>
</C>
<S i="60" s="1009" l="0" it="257">
<M n="24" v="0.008961"/><M n="25" v="0.008961"/>
</S>
</PF>
</C>
<S i="61" s="1006" l="0" it="331">
<M n="24" v="0.006971"/><M n="25" v="0.006971"/>
</S>
</PF>
</C>
<S i="62" s="680" l="0" it="791">
<M n="24" v="0.011947"/><M n="25" v="0.011947"/>
</S>
</PF>
</C>
<C i="63" s="499" l="728" v="0x402de8">
<M n="24" v="0.030889"/>
<PF i="64" s="681" l="0" lm="673" f="674" n="681">
<M n="24" v="0.030889"/><M n="25" v="0.000996"/>
<C i="65" s="682" l="0" v="0x7a8e5">
<M n="24" v="0.029893"/>
<PF i="66" s="1010" l="0" lm="1003" f="1004" n="1010">
<M n="24" v="0.029893"/><M n="25" v="0.014951"/>
<C i="67" s="1011" l="0" v="0x8d67">
<M n="24" v="0.014942"/>
<PF i="68" s="1012" l="0" lm="1003" f="1004" n="1012">
<M n="24" v="0.014942"/><M n="25" v="0.010955"/>
<C i="69" s="1013" l="0" v="0x19597">
<M n="24" v="0.003987"/>
<PF i="70" s="864" l="0" lm="858" f="859" n="864">
<M n="24" v="0.002992"/><M n="25" v="0.002992"/>
<S i="71" s="865" l="0" it="671">
<M n="24" v="0.002992"/><M n="25" v="0.002992"/>
</S>
</PF>
<PF i="72" s="1024" l="0" lm="1003" f="1004" n="1024">
<M n="24" v="0.000995"/><M n="25" v="0.000995"/>
<S i="73" s="1025" l="0" it="413">
<M n="24" v="0.000995"/><M n="25" v="0.000995"/>
</S>
</PF>
</C>
<S i="74" s="1013" l="0" it="389">
<M n="24" v="0.010955"/><M n="25" v="0.010955"/>
</S>
</PF>
</C>
<S i="75" s="1011" l="0" it="325">
<M n="24" v="0.014951"/><M n="25" v="0.014951"/>
</S>
</PF>
</C>
<S i="76" s="682" l="0" it="641">
<M n="24" v="0.000996"/><M n="25" v="0.000996"/>
</S>
</PF>
</C>
<C i="77" s="502" l="739" v="0x402b6e">