<?xml version="1.0"?>
<!DOCTYPE HPCToolkitExperiment [
<!-- ******************************************************************** -->
<!-- HPCToolkit Experiment DTD						  -->
<!-- Version 2.2							  -->
<!-- ******************************************************************** -->
<!ELEMENT HPCToolkitExperiment (Header, (SecCallPathProfile|SecFlatProfile)*)>
<!ATTLIST HPCToolkitExperiment
	  version CDATA #REQUIRED>

  <!-- ****************************************************************** -->

  <!-- Info/NV: flexible name-value pairs: (n)ame; (t)ype; (v)alue -->
  <!ELEMENT Info (NV*)>
  <!ATTLIST Info
	    n CDATA #IMPLIED>
  <!ELEMENT NV EMPTY>
  <!ATTLIST NV
	    n CDATA #REQUIRED
	    t CDATA #IMPLIED
	    v CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Header								  -->
  <!-- ****************************************************************** -->
  <!ELEMENT Header (Info*)>
  <!ATTLIST Header
	    n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section Header							  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecHeader (MetricTable?, MetricDBTable?, TraceDBTable?, LoadModuleTable?, FileTable?, ProcedureTable?, Info*)>

    <!-- MetricTable: -->
    <!ELEMENT MetricTable (Metric)*>

    <!-- Metric: (i)d; (n)ame -->
    <!--   o: metric sequence order (hpcrun metric order) -->
    <!--   md: metric description -->
    <!--   mp: metric parent ID   -->
    <!--   es: number of samples    (perf_events only) -->
    <!--   em: event multiplexed    (perf_events only) -->
    <!--   ep: average event period (perf_events only) -->
    <!--   (v)alue-type: transient type of values -->
    <!--   (t)ype: persistent type of metric      -->
    <!--   show: metric visibility type. Possible values: -->
    <!--        0: hidden -->
    <!--        1: shown  -->
    <!--        2: show inclusive metric only -->
    <!--        3: show exclusive metric only -->
    <!--        4: invisible, do not show at all -->
    <!--   show-percent: whether to show the percent (1) or not (0)  -->
    <!--   partner: the exclusive or inclusive partner ID of this metric -->
    <!--   fmt: format; show; -->
    <!ELEMENT Metric (MetricFormula*, Info?)>
    <!ATTLIST Metric
	      i            CDATA #REQUIRED
	      o	           CDATA #IMPLIED
	      n            CDATA #REQUIRED
	      md           CDATA #IMPLIED
	      mp           CDATA #IMPLIED
	      es           CDATA #IMPLIED
	      em           CDATA #IMPLIED
	      ep           CDATA #IMPLIED
	      v            (raw|final|derived-incr|derived) "raw"
	      t            (inclusive|exclusive|nil) "nil"
	      partner      CDATA #IMPLIED
	      fmt          CDATA #IMPLIED
	      show         (1|0|2|3|4) "1"
	      show-percent (1|0) "1">

    <!-- MetricFormula represents derived metrics: (t)ype; (frm): formula -->
    <!ELEMENT MetricFormula (Info?)>
    <!ATTLIST MetricFormula
	      t   (combine|finalize|view) "finalize"
	      i   CDATA #IMPLIED
	      frm CDATA #REQUIRED>

    <!-- Metric data, used in sections: (n)ame [from Metric]; (v)alue -->
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	      n CDATA #REQUIRED
	      v CDATA #REQUIRED>

    <!-- MetricDBTable: -->
    <!ELEMENT MetricDBTable (MetricDB)*>

    <!-- MetricDB: (i)d; (n)ame -->
    <!--   (t)ype: persistent type of metric -->
    <!--   db-glob:        file glob describing files in metric db -->
    <!--   db-id:          id within metric db -->
    <!--   db-num-metrics: number of metrics in db -->
    <!--   db-header-sz:   size (in bytes) of a db file header -->
    <!ELEMENT MetricDB EMPTY>
    <!ATTLIST MetricDB
	      i              CDATA #REQUIRED
	      n              CDATA #REQUIRED
	      t              (inclusive|exclusive|nil) "nil"
	      partner        CDATA #IMPLIED
	      db-glob        CDATA #IMPLIED
	      db-id          CDATA #IMPLIED
	      db-num-metrics CDATA #IMPLIED
	      db-header-sz   CDATA #IMPLIED>

    <!-- TraceDBTable: -->
    <!ELEMENT TraceDBTable (TraceDB)>

    <!-- TraceDB: (i)d -->
    <!--   u: unit time of the trace (ms, ns, ..) -->
    <!--   db-min-time: min beginning time stamp (global) -->
    <!--   db-max-time: max ending time stamp (global) -->
    <!ELEMENT TraceDB EMPTY>
    <!ATTLIST TraceDB
	      i            CDATA #REQUIRED
	      u            CDATA #IMPLIED
	      db-glob      CDATA #IMPLIED
	      db-min-time  CDATA #IMPLIED
	      db-max-time  CDATA #IMPLIED
	      db-header-sz CDATA #IMPLIED>

    <!-- LoadModuleTable assigns a short name to a load module -->
    <!ELEMENT LoadModuleTable (LoadModule)*>

    <!ELEMENT LoadModule (Info?)>
    <!ATTLIST LoadModule
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- FileTable assigns a short name to a file -->
    <!ELEMENT FileTable (File)*>

    <!ELEMENT File (Info?)>
    <!ATTLIST File
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- ProcedureTable assigns a short name to a procedure -->
    <!ELEMENT ProcedureTable (Procedure)*>

    <!-- Dictionary for procedure: (i)d, (n)ame, (f)eature and (v)alue of the address -->
    <!-- Possible value of f: -->
    <!-- 0: normal procedure -->
    <!-- 1: place holder, do not add anything -->
    <!-- 2: root-type, has to be shown in a separate view -->
    <!-- 3: invisible in hpcviewer, but visible in hpctraceviewer  -->
    <!ELEMENT Procedure (Info?)>
    <!ATTLIST Procedure
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED
	      f CDATA #IMPLIED
	      v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Call path profile					  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecCallPathProfile (SecHeader, SecCallPathProfileData)>
  <!ATTLIST SecCallPathProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecCallPathProfileData (PF|M)*>
      <!-- Procedure frame -->
      <!--   (i)d: unique identifier for cross referencing -->
      <!--   (s)tatic scope id -->
      <!--   (n)ame: a string or an id in ProcedureTable -->
      <!--   (lm) load module: a string or an id in LoadModuleTable -->
      <!--   (f)ile name: a string or an id in LoadModuleTable -->
      <!--   (l)ine range: "beg-end" (inclusive range) -->
      <!--   (a)lien: whether frame is alien to enclosing P -->
      <!--   (str)uct: hpcstruct node id -->
      <!--   (v)ma-range-set: "{[beg-end), [beg-end)...}" -->
      <!ELEMENT PF (PF|Pr|L|C|S|M)*>
      <!ATTLIST PF
		i  CDATA #IMPLIED
		s  CDATA #IMPLIED
		n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Procedure (static): GOAL: replace with 'P' -->
      <!ELEMENT Pr (Pr|L|C|S|M)*>
      <!ATTLIST Pr
                i  CDATA #IMPLIED
		s  CDATA #IMPLIED
                n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
                l  CDATA #IMPLIED
		a  (1|0) "0"
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Callsite (a special StatementRange) -->
      <!ELEMENT C (PF|M)*>
      <!ATTLIST C
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Flat profile						  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecFlatProfile (SecHeader, SecFlatProfileData)>
  <!ATTLIST SecFlatProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecFlatProfileData (LM|M)*>
      <!-- Load module: (i)d; (n)ame; (v)ma-range-set -->
      <!ELEMENT LM (F|P|M)*>
      <!ATTLIST LM
                i CDATA #IMPLIED
                n CDATA #REQUIRED
		v CDATA #IMPLIED>
      <!-- File -->
      <!ELEMENT F (P|L|S|M)*>
      <!ATTLIST F
                i CDATA #IMPLIED
                n CDATA #REQUIRED>
      <!-- Procedure (Note 1) -->
      <!ELEMENT P (P|A|L|S|C|M)*>
      <!ATTLIST P
                i CDATA #IMPLIED
                n CDATA #REQUIRED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Alien (Note 1) -->
      <!ELEMENT A (A|L|S|C|M)*>
      <!ATTLIST A
                i CDATA #IMPLIED
                f CDATA #IMPLIED
                n CDATA #IMPLIED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Loop (Note 1,2) -->
      <!ELEMENT L (A|Pr|L|S|C|M)*>
      <!ATTLIST L
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
	        f CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Statement (Note 2) -->
      <!--   (it): trace record identifier -->
      <!ELEMENT S (S|M)*>
      <!ATTLIST S
		i  CDATA #IMPLIED
		it CDATA #IMPLIED
		s  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Note 1: Contained Cs may not contain PFs -->
      <!-- Note 2: The 's' attribute is not used for flat profiles -->
]>
<HPCToolkitExperiment version="2.2">
<Header n="miniapp">
  <Info/>
</Header>
<SecCallPathProfile i="0" n="miniapp">
<SecHeader>
  <MetricTable>
    <Metric i="24" n="CPUTIME (sec):Sum (I)" o="0" v="derived-incr" md="CPUTIME (sec)" em="0" es="0" ep="0" t="inclusive" partner="25" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($24, $24)"/>
      <MetricFormula t="finalize" frm="$24"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="25" n="CPUTIME (sec):Sum (E)" o="-1" v="derived-incr" md="CPUTIME (sec)" em="0" es="0" ep="0" t="exclusive" partner="24" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($25, $25)"/>
      <MetricFormula t="finalize" frm="$25"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
  </MetricTable>
  <MetricDBTable>
  </MetricDBTable>
  <TraceDBTable>
    <TraceDB i="0" u="1000000000" db-glob="*.hpctrace" db-min-time="1596577253650419000" db-max-time="1596577313437265000" db-header-sz="32"/>
  </TraceDBTable>
  <LoadModuleTable>
    <LoadModule i="2" n="/home/u10/ianbertolacci/testcode/HPCToolkit-Testing-Miniapp/mpi_omp/miniapp"/>
    <LoadModule i="653" n="/opt/ohpc/pub/apps/hpctoolkit/2020.06/linux-centos7-zen/gcc-8.3.0/hpctoolkit-2020.06.12-eihbyb4brvhwsp2znuoxozo7uwus7y4n/lib/hpctoolkit/libhpcrun.so.0.0.0"/>
    <LoadModule i="657" n="/opt/ohpc/pub/apps/hpctoolkit/2020.06/linux-centos7-zen/gcc-8.3.0/hpctoolkit-2020.06.12-eihbyb4brvhwsp2znuoxozo7uwus7y4n/lib/hpctoolkit/ext-libs/libmonitor.so.0.0.0"/>
    <LoadModule i="669" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/libmpi.so.40.10.4"/>
    <LoadModule i="696" n="/opt/ohpc/pub/compiler/gcc/8.3.0/lib64/libgomp.so.1.0.0"/>
    <LoadModule i="827" n="/usr/lib64/libpthread-2.17.so"/>
    <LoadModule i="838" n="/usr/lib64/libc-2.17.so"/>
    <LoadModule i="859" n="/usr/lib64/ld-2.17.so"/>
    <LoadModule i="873" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/libopen-rte.so.40.10.4"/>
    <LoadModule i="886" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/libopen-pal.so.40.10.4"/>
    <LoadModule i="939" n="/usr/lib64/libevent-2.0.so.5.1.9"/>
    <LoadModule i="945" n="/usr/lib64/libevent_pthreads-2.0.so.5.1.9"/>
    <LoadModule i="953" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_ess_pmi.so"/>
    <LoadModule i="959" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_pmix_ext2x.so"/>
    <LoadModule i="965" n="/opt/ohpc/admin/pmix/lib/libpmix.so.2.1.22"/>
    <LoadModule i="988" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_routed_binomial.so"/>
    <LoadModule i="992" n="/usr/lib64/libbnxt_re-rdmav22.so"/>
    <LoadModule i="1044" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_btl_vader.so"/>
    <LoadModule i="1055" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_btl_openib.so"/>
    <LoadModule i="1066" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_pml_ob1.so"/>
    <LoadModule i="1097" n="/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib/openmpi/mca_coll_tuned.so"/>
  </LoadModuleTable>
  <FileTable>
    <File i="3" n="./src/home/u10/ianbertolacci/testcode/HPCToolkit-Testing-Miniapp/mpi_omp/miniapp.c"/>
    <File i="553" n="&lt;unknown file&gt; [miniapp]"/>
    <File i="654" n="&lt;unknown file&gt; [libhpcrun.so.0.0.0]"/>
    <File i="658" n="&lt;unknown file&gt; [libmonitor.so.0.0.0]"/>
    <File i="670" n="&lt;unknown file&gt; [libmpi.so.40.10.4]"/>
    <File i="683" n="pfile_iwrite_at.c"/>
    <File i="697" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/parallel.c"/>
    <File i="709" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/libgomp.h"/>
    <File i="717" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/team.c"/>
    <File i="740" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/posix/pool.h"/>
    <File i="721" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/alloc.c"/>
    <File i="729" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/work.c"/>
    <File i="814" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/linux/ptrlock.h"/>
    <File i="758" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/task.c"/>
    <File i="780" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/linux/bar.c"/>
    <File i="787" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/linux/x86/futex.h"/>
    <File i="790" n="/home/abuild/rpmbuild/BUILD/gcc-8.3.0/obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/config/linux/bar.h"/>
    <File i="828" n="&lt;unknown file&gt; [libpthread-2.17.so]"/>
    <File i="833" n="pthread_getschedparam.c"/>
    <File i="839" n="ioungetwc.c"/>
    <File i="848" n="&lt;unknown file&gt; [libc-2.17.so]"/>
    <File i="860" n="rtld-memcmp.c"/>
    <File i="874" n="&lt;unknown file&gt; [libopen-rte.so.40.10.4]"/>
    <File i="881" n="regx_base_default_fns.c"/>
    <File i="887" n="&lt;unknown file&gt; [libopen-pal.so.40.10.4]"/>
    <File i="892" n="opal_finalize.c"/>
    <File i="940" n="&lt;unknown file&gt; [libevent-2.0.so.5.1.9]"/>
    <File i="946" n="&lt;unknown file&gt; [libevent_pthreads-2.0.so.5.1.9]"/>
    <File i="954" n="ess_pmi_component.c"/>
    <File i="960" n="&lt;unknown file&gt; [mca_pmix_ext2x.so]"/>
    <File i="966" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/client/pmix_client.c"/>
    <File i="972" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/runtime/pmix_progress_threads.c"/>
    <File i="982" n="/home/abuild/rpmbuild/BUILD/pmix-2.2.2/src/class/pmix_object.h"/>
    <File i="989" n="crtstuff.c"/>
    <File i="993" n="&lt;unknown file&gt; [libbnxt_re-rdmav22.so]"/>
    <File i="1045" n="&lt;unknown file&gt; [mca_btl_vader.so]"/>
    <File i="1048" n="crtstuff.c"/>
    <File i="1056" n="crtstuff.c"/>
    <File i="1061" n="&lt;unknown file&gt; [mca_btl_openib.so]"/>
    <File i="1067" n="&lt;unknown file&gt; [mca_pml_ob1.so]"/>
    <File i="1070" n="pml_ob1_sendreq.c"/>
    <File i="1098" n="&lt;unknown file&gt; [mca_coll_tuned.so]"/>
  </FileTable>
  <ProcedureTable>
    <Procedure i="64" n="in_place_stencilize_local_array._omp_fn.3" v="0x401770"/>
    <Procedure i="459" n="in_place_stencilize_distributed_array" v="0x402ac0"/>
    <Procedure i="509" n="" v="0"/>
    <Procedure i="510" n="in_place_stencilize_local_array" v="0"/>
    <Procedure i="71" n="sum_local_array._omp_fn.4" v="0x4018f0"/>
    <Procedure i="527" n="sum_distributed_array" v="0x402ed0"/>
    <Procedure i="548" n="sum_local_array" v="0"/>
    <Procedure i="4" n="main" v="0x401200"/>
    <Procedure i="37" n="program_finalize" v="0"/>
    <Procedure i="573" n="MPI_Isend@plt" v="0x401050"/>
    <Procedure i="575" n="malloc@plt" v="0x401060"/>
    <Procedure i="595" n="MPI_Wait@plt" v="0x401100"/>
    <Procedure i="655" n="&lt;no activity&gt;" f="3" v="0"/>
    <Procedure i="659" n="&lt;program root&gt;" f="4" v="0"/>
    <Procedure i="665" n="MPI_Finalize" v="0"/>
    <Procedure i="667" n="&lt;thread root&gt;" f="4" v="0"/>
    <Procedure i="675" n="MPI_Isend" v="0"/>
    <Procedure i="677" n="PMPI_Irecv" v="0"/>
    <Procedure i="679" n="MPI_Wait" v="0"/>
    <Procedure i="681" n="ompi_request_default_wait" v="0"/>
    <Procedure i="686" n="PMPI_Gather" v="0"/>
    <Procedure i="688" n="ompi_coll_base_gather_intra_basic_linear" v="0"/>
    <Procedure i="690" n="ompi_datatype_sndrcv" v="0"/>
    <Procedure i="692" n="opal_datatype_copy_content_same_ddt@plt" v="0"/>
    <Procedure i="694" n="ompi_mpi_finalize" v="0"/>
    <Procedure i="684" n="ompi_request_empty_free" v="0"/>
    <Procedure i="707" n="gomp_resolve_num_threads" v="0"/>
    <Procedure i="709" n="&lt;inline&gt;" v="0"/>
    <Procedure i="698" n="GOMP_parallel_end" v="0"/>
    <Procedure i="700" n="&lt;inline&gt;" v="0"/>
    <Procedure i="704" n="GOMP_parallel" v="0"/>
    <Procedure i="769" n="omp_get_num_threads" v="0"/>
    <Procedure i="773" n="omp_get_thread_num" v="0"/>
    <Procedure i="718" n="gomp_new_team" v="0"/>
    <Procedure i="740" n="&lt;inline&gt;" v="0"/>
    <Procedure i="742" n="&lt;inline&gt;" v="0"/>
    <Procedure i="744" n="gomp_team_start" v="0"/>
    <Procedure i="777" n="gomp_team_end" v="0"/>
    <Procedure i="722" n="gomp_malloc" v="0"/>
    <Procedure i="730" n="gomp_init_work_share" v="0"/>
    <Procedure i="814" n="&lt;inline&gt;" v="0"/>
    <Procedure i="799" n="gomp_fini_work_share" v="0"/>
    <Procedure i="759" n="gomp_init_task" v="0"/>
    <Procedure i="761" n="&lt;inline&gt;" v="0"/>
    <Procedure i="802" n="gomp_end_task" v="0"/>
    <Procedure i="805" n="&lt;inline&gt;" v="0"/>
    <Procedure i="781" n="gomp_team_barrier_wait_end" v="0"/>
    <Procedure i="787" n="&lt;inline&gt;" v="0"/>
    <Procedure i="791" n="gomp_barrier_wait_final_start" v="0"/>
    <Procedure i="795" n="&lt;inline&gt;" v="0"/>
    <Procedure i="829" n="pthread_spin_lock" v="0"/>
    <Procedure i="831" n="pthread_spin_init" v="0"/>
    <Procedure i="836" n="pthread_mutex_unlock" v="0"/>
    <Procedure i="834" n="__pthread_self" v="0"/>
    <Procedure i="840" n="__memcpy_ssse3" v="0"/>
    <Procedure i="842" n="__GI___libc_malloc" v="0"/>
    <Procedure i="844" n="_int_malloc" v="0"/>
    <Procedure i="846" n="malloc_consolidate" v="0"/>
    <Procedure i="851" n="_int_free" v="0"/>
    <Procedure i="857" n="__epoll_wait_nocancel" v="0"/>
    <Procedure i="849" n="free" v="0"/>
    <Procedure i="853" n="__sched_yield" v="0"/>
    <Procedure i="855" n="syscall" v="0"/>
    <Procedure i="861" n="_dl_runtime_resolve_xsavec" v="0"/>
    <Procedure i="863" n="_dl_fixup" v="0"/>
    <Procedure i="865" n="_dl_lookup_symbol_x" v="0"/>
    <Procedure i="867" n="do_lookup_x" v="0"/>
    <Procedure i="869" n="check_match.9525" v="0"/>
    <Procedure i="871" n="strcmp" v="0"/>
    <Procedure i="877" n="orte_finalize" v="0"/>
    <Procedure i="879" n="orte_ess_base_app_finalize" v="0"/>
    <Procedure i="884" n="orte_session_dir_finalize" v="0"/>
    <Procedure i="882" n="orte_routed_base_close" v="0"/>
    <Procedure i="895" n="opal_convertor_prepare_for_send" v="0"/>
    <Procedure i="897" n="opal_convertor_prepare_for_recv" v="0"/>
    <Procedure i="899" n="opal_convertor_unpack" v="0"/>
    <Procedure i="901" n="opal_progress" v="0"/>
    <Procedure i="905" n="memcpy@plt" v="0"/>
    <Procedure i="909" n="opal_datatype_copy_content_same_ddt" v="0"/>
    <Procedure i="911" n="mca_base_framework_close" v="0"/>
    <Procedure i="915" n="opal_hash_table_get_value_ptr" v="0"/>
    <Procedure i="925" n="opal_os_dirpath_destroy" v="0"/>
    <Procedure i="927" n="opal_os_path" v="0"/>
    <Procedure i="929" n="opal_finalize_util" v="0"/>
    <Procedure i="931" n="mca_base_var_finalize" v="0"/>
    <Procedure i="935" n="mca_base_var_group_finalize" v="0"/>
    <Procedure i="893" n="opal_convertor_construct" v="0"/>
    <Procedure i="903" n="opal_timer_linux_get_cycles_sys_timer" v="0"/>
    <Procedure i="907" n="non_overlap_copy_content_same_ddt" v="0"/>
    <Procedure i="913" n="group_find" v="0"/>
    <Procedure i="917" n="mca_btl_base_close" v="0"/>
    <Procedure i="919" n="intercept_munmap" v="0"/>
    <Procedure i="921" n="opal_free_list_destruct" v="0"/>
    <Procedure i="923" n="opal_free_list_allocation_release" v="0"/>
    <Procedure i="933" n="var_destructor" v="0"/>
    <Procedure i="937" n="mca_base_var_group_destructor" v="0"/>
    <Procedure i="941" n="event_base_loop" v="0"/>
    <Procedure i="943" n="_event_strlcpy" v="0"/>
    <Procedure i="947" n="&lt;unknown procedure&gt; 0xf00 [libevent_pthreads-2.0.so.5.1.9]" v="0"/>
    <Procedure i="949" n="&lt;unknown procedure&gt; 0xef0 [libevent_pthreads-2.0.so.5.1.9]" v="0"/>
    <Procedure i="951" n="&lt;unknown procedure&gt; 0xef3 [libevent_pthreads-2.0.so.5.1.9]" v="0"/>
    <Procedure i="957" n="rte_finalize" v="0"/>
    <Procedure i="963" n="ext2x_client_finalize" v="0"/>
    <Procedure i="979" n="PMIx_Finalize" v="0"/>
    <Procedure i="984" n="tracker_destructor" v="0"/>
    <Procedure i="986" n="progress_engine" v="0"/>
    <Procedure i="981" n="pmix_progress_thread_stop" v="0"/>
    <Procedure i="982" n="&lt;inline&gt;" v="0"/>
    <Procedure i="990" n="finalize" v="0"/>
    <Procedure i="994" n="&lt;unknown procedure&gt; 0x3870 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="996" n="&lt;unknown procedure&gt; 0x3872 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="998" n="&lt;unknown procedure&gt; 0x3893 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1000" n="&lt;unknown procedure&gt; 0x389c [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1002" n="&lt;unknown procedure&gt; 0x38b4 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1004" n="&lt;unknown procedure&gt; 0x38bd [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1006" n="&lt;unknown procedure&gt; 0x3994 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1008" n="&lt;unknown procedure&gt; 0x2c90 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1010" n="&lt;unknown procedure&gt; 0x2c92 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1014" n="&lt;unknown procedure&gt; 0x2c9d [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1016" n="&lt;unknown procedure&gt; 0x2cba [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1018" n="&lt;unknown procedure&gt; 0x2cd0 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1020" n="&lt;unknown procedure&gt; 0x3063 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1026" n="&lt;unknown procedure&gt; 0x39fd [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1028" n="&lt;unknown procedure&gt; 0x3ab9 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1030" n="&lt;unknown procedure&gt; 0x38b0 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1032" n="&lt;unknown procedure&gt; 0x3988 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1034" n="&lt;unknown procedure&gt; 0x2c99 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1040" n="&lt;unknown procedure&gt; 0x5238 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1042" n="&lt;unknown procedure&gt; 0x5924 [libbnxt_re-rdmav22.so]" v="0"/>
    <Procedure i="1046" n="mca_btl_vader_sendi" v="0"/>
    <Procedure i="1051" n="mca_btl_vader_poll_handle_frag" v="0"/>
    <Procedure i="1053" n="memcpy@plt" v="0"/>
    <Procedure i="1049" n="mca_btl_vader_component_progress" v="0"/>
    <Procedure i="1057" n="btl_openib_component_progress" v="0"/>
    <Procedure i="1059" n="poll_device" v="0"/>
    <Procedure i="1064" n="device_destruct" v="0"/>
    <Procedure i="1062" n="mca_btl_openib_finalize" v="0"/>
    <Procedure i="1068" n="mca_pml_ob1_isend" v="0"/>
    <Procedure i="1073" n="mca_pml_ob1_irecv" v="0"/>
    <Procedure i="1075" n="mca_pml_ob1_recv_req_start" v="0"/>
    <Procedure i="1077" n="mca_pml_ob1_recv_request_progress_match" v="0"/>
    <Procedure i="1081" n="mca_pml_ob1_recv_frag_callback_match" v="0"/>
    <Procedure i="1087" n="memcpy@plt" v="0"/>
    <Procedure i="1089" n="opal_convertor_prepare_for_recv@plt" v="0"/>
    <Procedure i="1091" n="mca_pml_ob1_recv" v="0"/>
    <Procedure i="1093" n="opal_progress@plt" v="0"/>
    <Procedure i="1095" n="mca_pml_ob1_send" v="0"/>
    <Procedure i="1071" n="mca_pml_ob1_send_inline.constprop.6" v="0"/>
    <Procedure i="1079" n="mca_pml_ob1_recv_request_free" v="0"/>
    <Procedure i="1083" n="match_one" v="0"/>
    <Procedure i="1085" n="append_frag_to_list" v="0"/>
    <Procedure i="1099" n="ompi_coll_tuned_gather_intra_dec_fixed" v="0"/>
  </ProcedureTable>
  <Info/>
</SecHeader>
<SecCallPathProfileData>
<M n="24" v="237.135"/>
<PF i="2" s="655" l="0" lm="653" f="654" n="655">
<S i="3" s="656" l="0" it="1727"/>
</PF>
<PF i="4" s="659" l="0" lm="657" f="658" n="659">
<M n="24" v="237.019"/>
<C i="5" s="660" l="0" v="0xd76a">
<M n="24" v="237.019"/>
<PF i="6" s="4" l="858" lm="2" f="3" n="4">
<M n="24" v="237.019"/><M n="25" v="0.133801"/>
<S i="7" s="5" l="858" it="139"/>
<L i="8" s="26" l="879" f="3" v="0x401280">
<M n="24" v="236.969"/><M n="25" v="0.133801"/>
<S i="9" s="29" l="884">
<M n="24" v="0.011975"/><M n="25" v="0.011975"/>
</S>
<S i="10" s="30" l="885">
<M n="24" v="0.089889"/><M n="25" v="0.089889"/>
</S>
<S i="11" s="31" l="890">
<M n="24" v="0.014965"/><M n="25" v="0.014965"/>
</S>
<C i="12" s="33" l="881" v="0x40128a">
<M n="24" v="148.483"/>
<PF i="13" s="459" l="695" lm="2" f="3" n="459">
<M n="24" v="148.483"/><M n="25" v="0.755901"/>
<S i="14" s="460" l="695" it="547">
<M n="24" v="0.007996"/><M n="25" v="0.007996"/>
</S>
<S i="15" s="461" l="697">
<M n="24" v="0.005996"/><M n="25" v="0.005996"/>
</S>
<S i="16" s="463" l="702">
<M n="24" v="0.008995"/><M n="25" v="0.008995"/>
</S>
<S i="17" s="464" l="703">
<M n="24" v="0.071867"/><M n="25" v="0.071867"/>
</S>
<S i="18" s="465" l="704">
<M n="24" v="0.01699"/><M n="25" v="0.01699"/>
</S>
<S i="19" s="467" l="720">
<M n="24" v="0.010989"/><M n="25" v="0.010989"/>
</S>
<S i="20" s="468" l="721">
<M n="24" v="0.004995"/><M n="25" v="0.004995"/>
</S>
<S i="21" s="471" l="728">
<M n="24" v="0.01198"/><M n="25" v="0.01198"/>
</S>
<S i="22" s="472" l="729">
<M n="24" v="0.003989"/><M n="25" v="0.003989"/>
</S>
<S i="23" s="477" l="739">
<M n="24" v="0.008987"/><M n="25" v="0.008987"/>
</S>
<S i="24" s="480" l="746">
<M n="24" v="0.004988"/><M n="25" v="0.004988"/>
</S>
<S i="25" s="483" l="766">
<M n="24" v="0.179688"/><M n="25" v="0.179688"/>
</S>
<S i="26" s="485" l="773">
<M n="24" v="0.108878"/><M n="25" v="0.108878"/>
</S>
<S i="27" s="486" l="774">
<M n="24" v="0.008989"/><M n="25" v="0.008989"/>
</S>
<S i="28" s="488" l="777">
<M n="24" v="0.100839"/><M n="25" v="0.100839"/>
</S>
<S i="29" s="490" l="782">
<M n="24" v="0.004994"/><M n="25" v="0.004994"/>
</S>
<S i="30" s="492" l="785">
<M n="24" v="0.099889"/><M n="25" v="0.099889"/>
</S>
<S i="31" s="493" l="791">
<M n="24" v="0.013988"/><M n="25" v="0.013988"/>
</S>
<S i="32" s="497" l="799">
<M n="24" v="0.068896"/><M n="25" v="0.068896"/>
</S>
<C i="33" s="498" l="721" v="0x402dab">
<M n="24" v="1.09714"/>
<PF i="34" s="573" l="0" lm="2" f="553" n="573">
<M n="24" v="0.003992"/><M n="25" v="0.003992"/>
<S i="35" s="574" l="0" it="1507">
<M n="24" v="0.003992"/><M n="25" v="0.003992"/>
</S>
</PF>
<PF i="36" s="675" l="0" lm="669" f="670" n="675">
<M n="24" v="1.09315"/><M n="25" v="0.336382"/>
<C i="37" s="676" l="0" v="0x7af25">
<M n="24" v="0.756766"/>
<PF i="38" s="1068" l="0" lm="1066" f="1067" n="1068">
<M n="24" v="0.756766"/><M n="25" v="0.232636"/>
<C i="39" s="1069" l="0" v="0xb8e7">
<M n="24" v="0.52413"/>
<PF i="40" s="1071" l="0" lm="1066" f="1070" n="1071">
<M n="24" v="0.52413"/><M n="25" v="0.17665"/>
<C i="41" s="1072" l="0" v="0xacb9">
<M n="24" v="0.00599"/>
<PF i="42" s="893" l="0" lm="886" f="892" n="893">
<M n="24" v="0.00599"/><M n="25" v="0.00599"/>
<S i="43" s="894" l="0" it="1593">
<M n="24" v="0.00599"/><M n="25" v="0.00599"/>
</S>
</PF>
</C>
<C i="44" s="1072" l="0" v="0xacf6">
<M n="24" v="0.023962"/>
<PF i="45" s="895" l="0" lm="886" f="887" n="895">
<M n="24" v="0.023962"/><M n="25" v="0.023962"/>
<S i="46" s="896" l="0" it="1051">
<M n="24" v="0.023962"/><M n="25" v="0.023962"/>
</S>
</PF>
</C>
<C i="47" s="1072" l="0" v="0xad68">
<M n="24" v="0.317528"/>
<PF i="48" s="1046" l="0" lm="1044" f="1045" n="1046">
<M n="24" v="0.317528"/><M n="25" v="0.184726"/>
<C i="49" s="1047" l="0" v="0x570f">
<M n="24" v="0.118826"/>
<PF i="50" s="840" l="0" lm="838" f="839" n="840">
<M n="24" v="0.118826"/><M n="25" v="0.118826"/>
<S i="51" s="841" l="0" it="735">
<M n="24" v="0.118826"/><M n="25" v="0.118826"/>
</S>
</PF>
</C>
<C i="52" s="1047" l="0" v="0x574d">
<M n="24" v="0.013976"/>
<PF i="53" s="840" l="0" lm="838" f="839" n="840">
<M n="24" v="0.009988"/><M n="25" v="0.009988"/>
<S i="54" s="841" l="0" it="1539">
<M n="24" v="0.009988"/><M n="25" v="0.009988"/>
</S>
</PF>
<PF i="55" s="1053" l="0" lm="1044" f="1045" n="1053">
<M n="24" v="0.003988"/><M n="25" v="0.003988"/>
<S i="56" s="1054" l="0" it="351">
<M n="24" v="0.003988"/><M n="25" v="0.003988"/>
</S>
</PF>
</C>
<S i="57" s="1047" l="0" it="1763">
<M n="24" v="0.184726"/><M n="25" v="0.184726"/>
</S>
</PF>
</C>
<S i="58" s="1072" l="0" it="649">
<M n="24" v="0.17665"/><M n="25" v="0.17665"/>
</S>
</PF>
</C>
<S i="59" s="1069" l="0" it="661">
<M n="24" v="0.232636"/><M n="25" v="0.232636"/>
</S>
</PF>
</C>
<S i="60" s="676" l="0" it="439">
<M n="24" v="0.336382"/><M n="25" v="0.336382"/>
</S>
</PF>
</C>
<C i="61" s="499" l="728" v="0x402de8">
<M n="24" v="1.07018"/>
<PF i="62" s="677" l="0" lm="669" f="670" n="677">
<M n="24" v="1.07018"/><M n="25" v="0.149798"/>
<C i="63" s="678" l="0" v="0x7a8e5">
<M n="24" v="0.920381"/>